### ISSUE TITLE
Make Contribution

### ISSUE THREAD

**Issue by msio** [cloudinary/cloudinary_angular#106]
Hi,
 How can I build the project locally to try it in my own project ? 
Thanks
Michal

**Comment by marissa-masangcay** [comment]
Hi Michal,

You can start by looking at our sample angular project located at this link below:

https://github.com/cloudinary/cloudinary_angular/tree/master/samples/photo_album

 It will give you a step-by-step guideline on how to get your Cloudinary project up and running. If you have any questions or issues with getting this project to work or anything else for that matter please feel free to open a support ticket at this link: 

https://support.cloudinary.com/hc/en-us/requests/new

Cheers,
Marissa

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
