### ISSUE TITLE
Angular1 supports Cl-background-image directive. why angular2 not supports cl-background-image directive?

### ISSUE THREAD

**Issue by nivashmani** [cloudinary/cloudinary_angular#107]
Hi, 
currently working in angular2. 
we used cl-background-image directive for rendering the images as background of the div.
It is working fine in angular 1.
However it is not working in the angular 2 applications.
Please explain if there is any way to achieve this.....

**Comment by roeeba** [comment]
Hi, @nivashmani. 
We currently don't support a "cl-background-image" directive. This directive was created by an unofficial Angular SDK - https://github.com/tinusn/cloudinary-angular - which I assume you're referring to. We currently don't support it for Angular2+ as well.
That being said, I've forwarded your inquiry to our product team to review, so we might end up supporting this in the future.

**Comment by bjornharvold** [comment]
This is a great feature to have :-) We've been bypassing the directive, in many instances, in favor of direct URL to set the CSS background image as it allows us more control over how the image gets displayed. 

If there is another way around this, I would love to find out.
