### ISSUE TITLE
tag image while uploading with 3rd party upload tools

### ISSUE THREAD

**Issue by jariwbh** [cloudinary/cloudinary_angular#112]
We are using ng2FileSelect as a 3rd Party upload tool to upload file on cloudinary. 

<input type="file" id="fileupload" #fileInput ng2FileSelect [style.display]="'none'" [uploader]="uploader"/>

We would like to attach fieldname to uploaded file a tag value. this is not working as no tag return in response.

**Comment by roeeba** [comment]
Hi, @jariwbh. Our sample uses ng2FileSelect and adds custom tags, please see https://github.com/cloudinary/cloudinary_angular/blob/master/samples/photo_album/app/js/photo-album/photo-upload.component.ts#L49

Let me know if it helps?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
