### ISSUE TITLE
Programatic use examples?

### ISSUE THREAD

**Issue by demiro** [cloudinary/cloudinary_angular#113]
I want to use it programatically so I could set the generated URL as css background-image
I saw an example like:

`this.imageUrl = Cloudinary.url(this.image.id, { format: 'jpg', gravity: 'face' });`

the problem is, Cloudinary obj does not exist.... so I imported is as in ngModule
import { Cloudinary } from 'cloudinary-core/cloudinary-core-shrinkwrap';

obviously still doesn't work...

would like to see examples of this working

**Comment by eitanp461** [comment]
@demiro here is an example of using Cloudinary's instance - https://github.com/cloudinary/cloudinary_angular/blob/master/samples/photo_album/app/js/model/photo-album.service.ts#L17

```
export class PhotoAlbum {

    constructor(private http: Http, private cloudinary: Cloudinary) {
    }

    getPhotos(): Observable<Photo[]> {
        console.log(this.cloudinary.url('sample', { format: 'jpg', gravity: 'face' }));
...

```

Outputs `http://res.cloudinary.com/eitanpeer/image/upload/g_face/sample.jpg` to the console

**Comment by demiro** [comment]
@eitanp461 : thank you! ... please put it in the documentation as well... there are examples for all the languages, missing react and angular form js side... cheers!

**Comment by eitanp461** [comment]
@demiro I'll pass it on to our docs team. Thanks for the feedback!

**Comment by demiro** [comment]
hm, sadly it doesn't work with the width and height params
this._cloudinary.url(this.image.id, { format: 'jpg', gravity: 'face', width: 250, height: 200 });

**Comment by eitanp461** [comment]
@demiro the way width and height parameters are interpreted depends on their usage. 

- **Without a crop mode** they are set as attributes on the created `<img>` tag.
The following code:
```cl.image("foo", { responsive: true, alt: "bar", className: "myclass", width: 250, height: 200})```
produces:
```<img alt="bar" class="myclass cld-responsive" src="https://res.cloudinary.com/demo/image/upload/foo" width="250" height="200" data-src-cache="https://res.cloudinary.com/demo/image/upload/foo">```

- **When a crop mode is added**, the width and height are also added to the transformation URL.
The following code:
```cl.image("foo", { crop: "crop", responsive: true, alt: "bar", className: "myclass", width: 250, height: 200})```
produces:
```<img alt="bar" class="myclass cld-responsive" src="https://res.cloudinary.com/demo/image/upload/c_crop,h_200,w_250/foo" width="250" height="200" data-src-cache="https://res.cloudinary.com/demo/image/upload/c_crop,h_200,w_250/foo">```

**Comment by demiro** [comment]
OK, makes sense... added the crop mode and it works

**Comment by jackieros** [comment]
Hi, the exact behavior for when width/height are included in transformation URL and/or as HTML attributes actually depends on which crop mode you use. Details can be found in the Notes section of the [image tag](https://cloudinary.com/documentation/image_transformations#embedding_images_in_web_pages) documentation.
