### ISSUE TITLE
Making Cloudinary Angular compatible with Angular 5

### ISSUE THREAD

**Issue by bjornharvold** [cloudinary/cloudinary_angular#114]
Was getting this error when trying to compile with Angular 5:

> WARNING in ./node_modules/@cloudinary/angular-4.x/node_modules/@angular/core/@angular/core.es5.js
> 5659:15-36 Critical dependency: the request of a dependency is an expression
>     at ImportLazyContextDependency.getWarnings (/Users/crash/git/traveliko/traveliko-spa-administration/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
>     at Compilation.reportDependencyErrorsAndWarnings (/Users/crash/git/traveliko/traveliko-spa-administration/node_modules/webpack/lib/Compilation.js:703:24)
>     at Compilation.finish (/Users/crash/git/traveliko/traveliko-spa-administration/node_modules/webpack/lib/Compilation.js:561:9)
>     at applyPluginsParallel.err (/Users/crash/git/traveliko/traveliko-spa-administration/node_modules/webpack/lib/Compiler.js:506:17)
>     at /Users/crash/git/traveliko/traveliko-spa-administration/node_modules/tapable/lib/Tapable.js:289:11
>     at _addModuleChain (/Users/crash/git/traveliko/traveliko-spa-administration/node_modules/webpack/lib/Compilation.js:507:11)
>     at processModuleDependencies.err (/Users/crash/git/traveliko/traveliko-spa-administration/node_modules/webpack/lib/Compilation.js:477:14)
>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
>  @ ./node_modules/@cloudinary/angular-4.x/node_modules/@angular/core/@angular/core.es5.js
>  @ ./node_modules/@cloudinary/angular-4.x/src/cloudinary.module.js
>  @ ./node_modules/@cloudinary/angular-4.x/index.js
>  @ ./src/app/app.module.ts
>  @ ./src/main.ts
>  @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by demiro** [comment]
yes, please... I'd like this as well, asap

**Comment by roeeba** [comment]
Hi @bjornharvold, @demiro. Our team is aware of this issue. We'll make sure to resolve this as soon as we can.

**Comment by bjornharvold** [comment]
Thank you! Make @eitanp461 work his magic :-)

**Comment by sangwin** [comment]
Is this issue fixed? I am getting same issue in Angular 5 project

**Comment by glauberramos** [comment]
I am getting the same error as well

**Comment by roeeba** [comment]
Hey guys, the issue hasn't resolved yet. While this isn't a trivial issue, we're aiming to deploy a fix in the next few months, though there's isn't a final ETA yet. We'll update here once we do have one.

**Comment by bjornharvold** [comment]
Hi @roeeba 

Can you elaborate on the complexity of this issue? Upgrading from 4.4.6 to 5.0.1 was a painless affair for all our applications and 90% of our other 3rd party libraries were already compatible. The other 10% were updated within a couple of days. Looking at Angular 5's change log of breaking changes, there are really none that stand out.

Just waiting for Cloudinary now to be able to use all the new goodness with Angular 5. Having to wait "a few months" for this is not the answer I was hoping for.

Cheers

**Comment by sangwin** [comment]
I am facing the same issue, However [This ng2-cloudinary](https://ekito.github.io/ng2-cloudinary/docs/) Plugin helped me out.

**Comment by roeeba** [comment]
Hi, @bjornharvold. Our dev team are working on this issue. While it's not complex, we still can't commit on an ETA at the moment. We're doing our best to resolve this ASAP.

**Comment by sangwin** [comment]
@roeeba  I still think a month is a lot more time to fix such an issue.

**Comment by yuricamara** [comment]
I am wondering if I should use another image service since I can't wait for months to use it with Angular 5.

**Comment by yuricamara** [comment]
Thank you very much for solving this issue, @eitanp461 .

When should it be a release with this merge?

**Comment by eitanp461** [comment]
@yuricamara The new version has been released.
All samples on `master` branch were updated to use Angular 5.

**Comment by yuricamara** [comment]
I have just updated my project with the new version.
I didn't see any issue. Congratulations, @eitanp461 

```
>   "dependencies": {
>     "@angular/common": "5.0.0",
>     "@angular/compiler": "5.0.0",
>     "@angular/compiler-cli": "5.0.0",
>     "@angular/core": "5.0.0",
>     "@angular/forms": "5.0.0",
>     "@angular/http": "5.0.0",
>     "@angular/platform-browser": "5.0.0",
>     "@angular/platform-browser-dynamic": "5.0.0",
>     "@angular/platform-server": "5.0.0",
>     "@cloudinary/angular-5.x": "1.0.0",
>     "@ionic-native/core": "4.4.0",
>     "@ionic-native/splash-screen": "4.4.0",
>     "@ionic-native/status-bar": "4.4.0",
>     "@ionic/cli-plugin-cordova": "1.6.2",
>     "@ionic/cli-plugin-ionic-angular": "1.4.1",
>     "@ionic/storage": "2.1.3",
>     "apollo-angular": "1.0.0",
>     "apollo-angular-link-http": "1.0.0",
>     "apollo-cache-inmemory": "1.1.0",
>     "apollo-client": "2.0.3",
>     "apollo-link": "1.0.0",
>     "cloudinary-core": "2.3.0",
>     "cordova-android": "6.3.0",
>     "cordova-plugin-console": "1.0.5",
>     "cordova-plugin-device": "1.1.4",
>     "cordova-plugin-splashscreen": "~4.0.1",
>     "cordova-plugin-statusbar": "2.2.1",
>     "cordova-plugin-whitelist": "1.3.1",
>     "cordova-sqlite-storage": "~2.0.3",
>     "graphql": "0.11.7",
>     "graphql-tag": "2.5.0",
>     "ionic-angular": "3.9.2",
>     "ionic-plugin-keyboard": "~2.2.1",
>     "ionicons": "3.0.0",
>     "rxjs": "5.5.2",
>     "sw-toolbox": "3.6.0",
>     "zone.js": "0.8.18"
>   },
> 
```

**Comment by bjornharvold** [comment]
Works here!! @eitanp461 great work brother :-)
