### ISSUE TITLE
I can't import CloudinaryModule to my Angular 5 app

### ISSUE THREAD

**Issue by Jonathan002** [cloudinary/cloudinary_angular#117]
I'm trying to import cloudinary to my AppModule:

```typescript
import { CloudinaryModule } from '@cloudinary/angular-4.x';
import * as  Cloudinary from 'cloudinary-core';

@NgModule({
  imports: [
      CloudinaryModule.forRoot(Cloudinary, { cloud_name: 'mycloudname'})
  ]
})
```

I get the following error in runtime when I start the app via `npm start`
```
Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.
```

It doesn't seem to recognize the configuration object or the module itself as I import it. I'm following the instructions from this [document](https://cloudinary.com/documentation/angular_integration). Am I using the right api or package for Angular 5?

**Comment by eitanp461** [comment]
@Jonathan002 Angular 5 is not supported yet, we'll be releasing the new SDK version later this week, see https://github.com/cloudinary/cloudinary_angular/issues/114

**Comment by Jonathan002** [comment]
Ok thanks for the quick response

**Comment by jackieros** [comment]
Eitan, 
Currently the docs just say Angular, and Angular 2+

If there will be anything specific we need to write in the docs about Angular 5 (other than that it is supported), please open a doc JIRA with the relevant info. Thx :-) 

⁣Jackie Rosenzveig
Technical Content Team Leader
Cell: 052-335-2779 
www.cloudinary.com​
