### ISSUE TITLE
request for new angular4 release

### ISSUE THREAD

**Issue by ctaepper** [cloudinary/cloudinary_angular#118]
there is a bug fixed in master #83 but not published to npm yet. we are currently workarounding this in a very ugly way. i am concerned, that with the upcoming release of the angular5 version #115 the bug won't be published to angular4 version anymore.

can you please give me some kind of info, if and when I can expect this bug to be published to angular-4.x version?

**Comment by eitanp461** [comment]
@ctaepper We've released SDK version `angular-4.x@^1.1.0`.
See updated usage in samples here - https://github.com/cloudinary/cloudinary_angular/commit/007ea2180e27ed60ac8edd817337f2cd4f8f2227
