### ISSUE TITLE
ReferenceError when used with nativescript-angular

### ISSUE THREAD

**Issue by nmongiya** [cloudinary/cloudinary_angular#119]
I am getting the below when I am trying to use <cl-image> in nativescript-angular app.
**ERROR ReferenceError: MutationObserver is not defined**. I am suspecting this is because there is no browser in the app and hence no support for MutationObserver

**Comment by roeeba** [comment]
Hi @nmongiya. Thank you for reporting this issue. Our dev team already handling this. We will update here as soon as this is resolved.
