### ISSUE TITLE
angular 4 native uploader

### ISSUE THREAD

**Issue by edwinquaihoi** [cloudinary/cloudinary_angular#122]
It would be much more user friendly to provide a native ng component for the cloudinary upload widget. This component should be integrated into the exist image and video component to provide edit and upload funtionality

**Comment by roeeba** [comment]
Hi @edwinquaihoi. Ir seems that our [upload widget](https://cloudinary.com/documentation/upload_widget#quick_example) is exactly what you're looking for. It is feature-rich, in active development, and can be used in any frontend project regardless of its tech stack.
In addition, we have a sample project demonstrating an integration with a native Angular upload component - https://github.com/cloudinary/cloudinary_angular/tree/master/samples/photo_album

**Comment by roeeba** [comment]
Hi @edwinquaihoi. The photo album sample project uses the open source file uploader [ng2-file-upload](https://github.com/valor-software/ng2-file-upload) and not Cloudinary's upload widget. 
Here is a basic example of how you can implement our upload widget in Angular2 - http://jsfiddle.net/roee_ba/7ovf0sbu/
(make sure to set your cloud_name and upload_preset were needed)

**Comment by netstart** [comment]
Widget not replace or delete image after upload. The actual version is not work to me

**Comment by strausr** [comment]
@netstart Can you please elaborate on how you're using the widget to replace an image? You can also open a support ticket at support@cloudinary.com with more details.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by tpiros** [comment]
It'd be great to have an Angular native implementation of the upload widget.

**Comment by strausr** [comment]
@tpiros Thanks for the feedback. Currently, as @roeeba  mentioned, the best approach would be to integrate the widget directly into your app.

**Comment by erperejildo** [comment]
Totally agree. If you do it get in touch with Ionic team to update their readme
