### ISSUE TITLE
Angular 5 AOT build fails

### ISSUE THREAD

**Issue by kadosh1000** [cloudinary/cloudinary_angular#125]
After upgrading to Angular 5 and @cloudinary/angular-5.x, trying to create an AOT build throws the following error:

![image](https://user-images.githubusercontent.com/2615945/34492885-200e0a06-eff2-11e7-9cb6-57ea9e310923.png)

**Comment by eitanp461** [comment]
@kadosh1000 Can you share your module creation code?
Have you seen our Angular CLI sample? It was tested for AOT builds.
Note how Cloudinary is instantiated - https://github.com/cloudinary/cloudinary_angular/blob/master/samples/angular-cli-sample/src/app/app.module.ts

Hope it helps.

**Comment by kadosh1000** [comment]
@eitanp461 It was my fault, I have forgotten to change all the import refrences from the 4.x to 5.x

I think that your package naming convention is problematic, I would recommend in the future maybe you should consider changing the naming convention, so the package would always be called for example `@cloudinary/angular` and maybe increase a major for each angular version (ie. v5.0.0)
