### ISSUE TITLE
CORS Problem Following example of photo_album

### ISSUE THREAD

**Issue by Crizstian** [cloudinary/cloudinary_angular#126]
I'm having the cors problem, and i have tried many things to avoid it, but it stills present

I'm using the cloudinary version 5 for angular and i have angular 5.2, this my configuration i am uploading it with ng2-file-upload

```
 const uploaderOptions: FileUploaderOptions = {
      url: `https://api.cloudinary.com/v1_1/${
        this.cloudinary.config().cloud_name
      }/upload`,
      autoUpload: false,
      isHTML5: true,
      removeAfterUpload: true,
      headers: [{ name: 'X-Requested-With', value: 'XMLHttpRequest' }]
    }
    this.uploader = new FileUploader(uploaderOptions)
```
Failed to load https://api.cloudinary.com/v1_1/producmex/upload: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. Origin 'http://localhost:4300' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by eitanp461** [comment]
@Crizstian I can't reproduce the problem. I've tried changing `autoUpload: false` since it is different than the example from the `photo_album` sample. I added a button that calls `uploader.uploadAll()` independently and upload still works.

Can you provide more details on your project, and the things you've tried so far to resolve this issue?
Can you provide a sample project?
Have you seen https://github.com/valor-software/ng2-file-upload/issues/140? Could the information there help you?

**Comment by Crizstian** [comment]
i have solved it with the following config in my module

```
import { Cloudinary } from 'cloudinary-core/cloudinary-core-shrinkwrap'
import {
  CloudinaryModule,
  CloudinaryConfiguration,
  provideCloudinary
} from '@cloudinary/angular-5.x'

const config: CloudinaryConfiguration = {
  cloud_name: 'xxx',
  api_key: 'xxx',
  api_secret: 'xxx-xxx',
  upload_preset: 'xxx'
}

const cloudinaryLib = {
  Cloudinary: Cloudinary
}
```

and for the uploading i was missing the `this.uploader.onBuildItemForm` function setting the parameters, now i am able to upload

but i think it is to blury to set all the configuration and the jquery dependency also, it has to many things that need to be fixed this library.
