### ISSUE TITLE
Bower and cloudinary_ng 1.0 coming back with empty src directory

### ISSUE THREAD

**Issue by selected-pixel-jameson** [cloudinary/cloudinary_angular#129]
I have a dependency using the cloudinary_ng library from Bower and it's pointing to version 1.0. All of a sudden I'm getting angular module errors and if I look at the bower directory for cloudinary_ng the src folder is empty. Has something changed with this?

**Comment by eitanp461** [comment]
@selected-pixel-jameson please update Cloudinary's dependency to ```"cloudinary_ng": "~1.x"``` which should resolve your issue.

On a general note, Bower's homepage has this discliamer
> ...psst! While Bower is maintained, we recommend using Yarn and Webpack for front-end projects read how to migrate!

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
