### ISSUE TITLE
cloudinary_ng 1.1.1 with webpack

### ISSUE THREAD

**Issue by tharrington** [cloudinary/cloudinary_angular#140]
Can we use this version with webpack? I am not able to get the module to resolve:

ERROR in ./~/cloudinary_ng/js/angular.cloudinary.js
Module not found: Error: Cannot resolve module 'cloudinary' in /Users/tyler/Desktop/test-api/node_modules/cloudinary_ng/js
 @ ./~/cloudinary_ng/js/angular.cloudinary.js 5:8-8:19

**Comment by roeeba** [comment]
Hi @tharrington, we're trying to reproduce the issue on our side. Can you please share with us your dependencies (`package.json`)?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
