### ISSUE TITLE
You must set the public id of the image to load, e.g. <cl-image public-id={{photo.public_id}}...></cl-image>

### ISSUE THREAD

**Issue by johnfrades** [cloudinary/cloudinary_angular#141]
Hi, im using Angular 5 and im getting this error 

`You must set the public id of the image to load, e.g. <cl-image public-id={{photo.public_id}}...></cl-image>`

Here is my code

` <cl-image public-id="{{myProfile?.profilePicture}}"
            class="thumbnail inline"
            angle="20"
            format="jpg">
  </cl-image>`

Basically myProfile is an object, and it's fetching from the backend.. Now im getting all the errors but the picture is there.

**Comment by strausr** [comment]
@johnfrades Is the image displaying for you? Can you please elaborate on the errors your seeing?

**Comment by johnfrades** [comment]
@strausr  yes the image is displayed, but after a few seconds, because i called it on the api backend. later when i get home i will paste the error. Thank you!

**Comment by johnfrades** [comment]
Here's the error 

![awgzxgqwahqa](https://user-images.githubusercontent.com/20201069/37762154-7519291a-2e20-11e8-991a-9f112e47ff8b.JPG)

so `authState$?.user.profilePicture` is the public id of the picture. I'm calling the backend to get it, thats why i put "?" on it.

**Comment by strausr** [comment]
@johnfrades can you please elaborate on what you're using to call your backend and what value is returned here authState$?.user.profilePicture?

Can you also specify the versions you're using?

**Comment by johnfrades** [comment]
I'm very sorry @strausr my apologies, it was that I forgot to load the `CloudinaryModule` into my child modules.
