### ISSUE TITLE
TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by erperejildo** [cloudinary/cloudinary_angular#142]
when I select an image to upload

**Comment by shirlymanor** [comment]
@erperejildo can you please share your code that causes this error? thanks

**Comment by erperejildo** [comment]
I just copied this component:
https://github.com/cloudinary/cloudinary_angular/tree/master/samples/photo_album/app/js/photo-album

**Comment by shirlymanor** [comment]
@erperejildo did you change the configurations as explained here: https://github.com/cloudinary/cloudinary_angular/tree/master/samples/photo_album

**Comment by erperejildo** [comment]
yes, in fact I tried first displaying one of my images and it worked. It might be related with `ng2-file-upload`

**Comment by strausr** [comment]
@erperejildo Did you install all the specified dependencies? Please share with us your project on support@cloudinary.com so that we can take a closer look

**Comment by erperejildo** [comment]
@strausr I tried first of all cloning this repo but it wasn't working. Maybe because I missed something on the config so I tried it out directly on mine which was already configured. 

This might be an issue on latest version of `ng2-file-upload` and I'm just creating confusion here:
https://github.com/valor-software/ng2-file-upload/issues/934

**Comment by erperejildo** [comment]
Yes, it might be related with that because I'm also getting this error now:
`Upload preset not found`
when the image is also selected:
<img width="351" alt="screen shot 2018-03-23 at 15 03 35" src="https://user-images.githubusercontent.com/5629919/37836820-6ae28884-2eab-11e8-820c-5134e35a9e78.png">
I'll close this issue, not related with this repo. Any help would be welcome tho

**Comment by erperejildo** [comment]
Found it: didn't have the preset configured. I thought this was optional.

My fault!

**Comment by sandeep18051989** [comment]
> I just copied this component:
> https://github.com/cloudinary/cloudinary_angular/tree/master/samples/photo_album/app/js/photo-album

Not found

**Comment by strausr** [comment]
@sandeep18051989 see #260 this will be handled in the next release.
