### ISSUE TITLE
Create thumbnail (question)

### ISSUE THREAD

**Issue by erperejildo** [cloudinary/cloudinary_angular#144]
On my example you can you choose a picture and after upload it to Cloudinary it will also save this reference on my Firebase ddbb to be displayed after on a different section of my app. 

This works perfectly I'd need to save also a thumbnail reference. How can I create this without pushing again a smaller image?

Using Angular 5

**Comment by shirlymanor** [comment]
@erperejildo When changing the URL on the fly it will create a derived image. in another word, you can just save the public id and if you are updating images you can save the version as well.

For example:

```
<cl-image 
    public-id="mypic" 
    format="jpg">
    <cl-transformation 
        height="200" 
        width="200" 
        crop="crop" >
    </cl-transformation>
</cl-image>
```

Here is more information about image manipulations with angular:
https://cloudinary.com/documentation/angular_image_manipulation

**Comment by erperejildo** [comment]
I display the information saved on Firebase which is just an url. I don't use Cloudinary to display anything, just to push these images.

```
<ion-card *ngFor="let recipe of recipes | async; let i = index">
    <img src="{{recipe.url}}" />
    <div class="title">{{recipe.title}}</div>
</ion-card>
```

I can save the reference instead the url and use that but I'd end up calling 2 different APIs and also (or maybe) making the client side a bit slower using this transformation for every image. My app has a layout like Instagram with too many images to display.

On the other hand I can have url and url_thumb on my Firebase ddbb but I'd have to push 2 different images from the client every time.

Can I do the second option but on the server side? Convert the image creating a thumbnail without pushing an extra image

**Comment by shirlymanor** [comment]
@erperejildo When using the `cl-image` with  `public-id` we are not calling the API. It's just string generation and it will not take much time and will not call the server side.

Alternatively, you can use [eager transformation](https://cloudinary.com/documentation/upload_images#eager_transformations) and create it when uploading the image (one call).

**Comment by shirlymanor** [comment]
@erperejildo 1. you can achieve this is both ways, both will work seamlessly.

a. When doing eager, as part of the response, we'll include the URL to the thumbnail version too, you can store that as a reference (e.g., `recipe.thumb_url`).
b. What we meant is that Cloudinary indeed does the transformation on our end, not on the client-side. 
For example, for an original image:
https://res.cloudinary.com/demo/image/upload/sample.jpg
By adding transformation on the fly (e.g. adding w_200) will create the transformed image on our backend, in this case:
https://res.cloudinary.com/demo/image/upload/w_200/sample.jpg

The option to save the public_id (in this case `sample`) can use later when creating those URL's.
Please let me know if that makes sense

**Comment by erperejildo** [comment]
If you say that this is not taking more time to be resized obviously the best option would be create the thumb on the fly. Also as a free user it's much better for me not creating unnecesary images.

Considering also this last thing in order to reduce the bandwidth the best approach in my opinion would be implementing both ways:
I won't create any thumbs but I'll storage the real image and the thumb using the eager transformation url. Also my app wouldn't need further setup to read the images using `cl-image`.

Thanks for your support!
