### ISSUE TITLE
Samples using an upload button (question)

### ISSUE THREAD

**Issue by erperejildo** [cloudinary/cloudinary_angular#145]
I've got your example working perfectly but I need to make the upload process with a button not after selecting the image.

I've been looking an example like this but I couldn't find something similar.

My problem is with events like `this.uploader.onProgressItem = (fileItem: any, progress: any) => {` how can I get this progress?

**Comment by strausr** [comment]
@erperejildo We don't have an Angular solution but you can You can bind to various progress update events and display a progress bar using our Jquery library- https://jsfiddle.net/fmyL8y7j

**Comment by eitanp461** [comment]
@erperejildo I created a branch where the file selection is separated from the upload part.
Please see https://github.com/cloudinary/cloudinary_angular/commit/067c5ed51063a343d662720eed9128ea2de824cf

You can check out the `eparate-file-choice-and-upload` branch and run the `photo-album` sample to test it.

**Comment by erperejildo** [comment]
@strausr thanks for your solution but I'd like be separated from jQuery

@eitanp461 that's awesome. I'll try it now and I'll let you know anything.
Just one question: I saw that you downgraded the version TS. Any reason?

**Comment by eitanp461** [comment]
@erperejildo the TS change is unrelated, it was changed to test https://github.com/cloudinary/cloudinary_angular/issues/137

**Comment by erperejildo** [comment]
Ah cool.

So the only thing I needed was remove `autoUpload: true` and add `this.uploader.uploadAll()` to my upload function.

Works perfectly. Thanks!

**Comment by erperejildo** [comment]
If this helps, I moved this to a provider in order to being used on different pages.

For that we need to move everything inside our provider (obv) but we need to replace the `OnInit` function to a normal one and create this `OnInit` on our class calling previous function.

More info here: https://github.com/valor-software/ng2-file-upload/issues/1007#issuecomment-381911966
