### ISSUE TITLE
Cannot read property 'CloudinaryJQuery' of null

### ISSUE THREAD

**Issue by Abhivendra** [cloudinary/cloudinary_angular#147]
"@cloudinary/angular-5.x": "^1.0.1",
"cloudinary-core": "^2.5.0",

Working fine on ng build --prod --aot=false. But giving this error on ng build --prod. 
Tried all the solutions of
https://github.com/cloudinary/cloudinary_angular/issues/92
https://github.com/cloudinary/cloudinary_angular/issues/73

Please resolve it ASAP. My app performance has reduced by 60% without ahead of time compilation.

**Comment by strausr** [comment]
@Abhivendra Can you please share with us more information on your implementation? For example, your module.ts that initialize the Cloudinary module?
What tools are you using for build/deploy?

**Comment by Abhivendra** [comment]
```
imports: [
    BrowserModule,
    BrowserAnimationsModule,
    SharedModule,
    ToastrModule.forRoot({
      progressBar: true,
      closeButton: true,
      preventDuplicates: true,
      progressAnimation: 'increasing',
      positionClass: 'toast-top-right',
      iconClasses: {
        error: 'toast-error',
        info: 'toast-info',
        success: 'toast-success',
        warning: 'toast-warning',
      }
    }),
    RouterModule.forRoot(AppRoutes),
    FormsModule,
    HttpClientModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader),
        deps: [HttpClient]
      }
    }),
    NgbModule.forRoot(),
    SidebarModule.forRoot(),
    CloudinaryModule.forRoot(Cloudinary, {cloud_name: '<cloud here>', upload_preset: '<name here>'}),)
  ],
```

**Comment by eitanp461** [comment]
@Abhivendra We're missing the code that sets up the module.

Please try the following:

```
import { Cloudinary as CloudinaryCore } from 'cloudinary-core';
...
export const cloudinary = {
  Cloudinary: CloudinaryCore
};
...

@NgModule({
  declarations: [
      ...
  ],
  imports: [
      ...
    CloudinaryModule.forRoot(cloudinary, config),
  ],
  ...
})
export class AppModule { }
```

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by IyiKuyoro** [comment]
Hello,

I just ran into this issue and the solution posted by @eitanp461 fixed it.

May I ask. Is it within the capacity of this team to update this documentation? https://cloudinary.com/documentation/angular_integration

**Comment by yakirp** [comment]
Hi @IyiKuyoro , I will check this with our Doc Team. Thanks :)
