### ISSUE TITLE
Signed image upload?

### ISSUE THREAD

**Issue by FREEZX** [cloudinary/cloudinary_angular#15]
Hi, i couldn't find any documentation about achieving signed image upload with this.
Is it possible? Any documentation on it?

**Comment by thenikso** [comment]
+1

**Comment by ombr** [comment]
+1 And I would like to have an example without dom manipulation inside the angular controller :
http://ng-learn.org/2014/01/Dom-Manipulations/

**Comment by tocker** [comment]
@FREEZX and @thenikso, signing a request requires knowledge of your _API secret_. For this reason client side code does not sign requests. It will be too easy to extract the API secret from the JavaScript code running on the browser.

As an alternative, you can use an upload preset, or a server side component to sign the request.

See [this blog post for further information](http://cloudinary.com/blog/direct_upload_made_easy_from_browser_or_mobile_app_to_the_cloud).

@ombr  - which dom manipulation are you referring to?

**Comment by FREEZX** [comment]
@tocker I understand that, but client side code should be able to prepare a request, the backend should sign it and then the client code can directly upload the image by sending it along with the signature.

**Comment by thenikso** [comment]
eventually I understood how use signed upload-presets generating the signature from my server:

- create a signed preset in cloudinary
- make an api that uses `cloudinary.utils.sign_request` (in python) to return a json with signed cloudinary upload request payload
- use angular-file-upload with that payload to upload the file

**Comment by igorauad** [comment]
Hi @thenikso, quick question: 'cloudinary.utils.sign_request' responds among other info with the 'api_key'. Is this ok regarding security (provided the Api secret is safely maintained in the backend)?

**Comment by thenikso** [comment]
Yes @igorauad that's all right, the `api_key` is not a private information (while the *api secret* is)

**Comment by igorauad** [comment]
Thanks @thenikso !

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
