### ISSUE TITLE
NameNodeMap is not defined

### ISSUE THREAD

**Issue by Tomdrouv1** [cloudinary/cloudinary_angular#150]
Hi,

I'm actually using @cloudinar/angular-5.x, version 1.0.1 and I notice an error during server side rendering for images which are call with clSrc directive :

` ERROR ReferenceError: NamedNodeMap is not defined
1|ssr-happ |     at isNamedNodeMap (/usr/share/nginx/html/happeero/node_modules/@cloudinary/angular-5.x/src/cloudinary.service.js:17:78)
1|ssr-happ |     at transformKeyNames (/usr/share/nginx/html/happeero/node_modules/@cloudinary/angular-5.x/src/cloudinary.service.js:37:14)
1|ssr-happ |     at Cloudinary.toCloudinaryAttributes (/usr/share/nginx/html/happeero/node_modules/@cloudinary/angular-5.x/src/cloudinary.service.js:117:23)
1|ssr-happ |     at CloudinaryImageSourceDirective.ngAfterViewInit (/usr/share/nginx/html/happeero/node_modules/@cloudinary/angular-5.x/src/cloudinary-image-source.directive.js:45:39)
1|ssr-happ |     at callProviderLifecycles (/usr/share/nginx/html/happeero/node_modules/@angular/core/bundles/core.umd.js:12786:18)
1|ssr-happ |     at callElementProvidersLifecycles (/usr/share/nginx/html/happeero/node_modules/@angular/core/bundles/core.umd.js:12753:13)
1|ssr-happ |     at callLifecycleHooksChildrenFirst (/usr/share/nginx/html/happeero/node_modules/@angular/core/bundles/core.umd.js:12736:29)
1|ssr-happ |     at checkAndUpdateView (/usr/share/nginx/html/happeero/node_modules/@angular/core/bundles/core.umd.js:13891:5)
1|ssr-happ |     at callViewAction (/usr/share/nginx/html/happeero/node_modules/@angular/core/bundles/core.umd.js:14233:21)
1|ssr-happ |     at execEmbeddedViewsAction (/usr/share/nginx/html/happeero/node_modules/@angular/core/bundles/core.umd.js:14191:17)`.

Thanks for your help.
P.S : Can't wait for Angular 6 version 😉

**Comment by eitanp461** [comment]
@Tomdrouv1 we have several samples using server side rendering which seem to work well.
Can you check https://github.com/cloudinary/cloudinary_angular/tree/master/samples/angular-universal-sample?
You can run the sample with `npm run build:ssr && npm run serve:ssr`.

BTW We have updated all of our samples to use Angular6.
Currently in a branch -
https://github.com/cloudinary/cloudinary_angular/tree/angular6/samples

**Comment by Tomdrouv1** [comment]
Hi @eitanp461 

I tried to run ssr examples but there is no clSrc directive for img tag in those.

This issue happens  when I'm using <img clSrc="a link">.

**Comment by eitanp461** [comment]
@Tomdrouv1 I fixed the SDK and added usage of clSrc and cl-video to the Angular universal sample
