### ISSUE TITLE
Upload more than one image

### ISSUE THREAD

**Issue by erperejildo** [cloudinary/cloudinary_angular#152]
This is just a question, not an issue.

I'm uploading my images perfectly also using Angular 5 but I was wondering if would be possible to upload more than one image at once.

The progress bar should be calculated for both. Would be this possible? If so, what's the best approach?

**Comment by strausr** [comment]
@erperejildo uploading multiple images is indeed possible. The progress bar is calculated using ng2-file-upload and is per upload, meaning for each upload a progress bar is generated. Please note that this is recommended since it is a better indicator of the upload success of a file.

**Comment by erperejildo** [comment]
I see... so it wouldn't be possible calculate the whole size and from this create a unique progress bar.

My idea is upload an image and create locally a thumbnail and push also this. Tbh I don't really mind to create a second (or mixed) progress bar because this thumbnail is going to be to small to bother the user with another progress bar.

How can I upload more than one image then?

**Comment by strausr** [comment]
@erperejildo I think I misunderstood your question. To upload multiple resources- you would need to make an upload call each time. You can see how this achieved on our sample photo album by selecting multiple resources- https://github.com/cloudinary/cloudinary_angular/tree/master/samples/photo_album

**Comment by erperejildo** [comment]
Sorry, my bad.

I want to **select** one image but I need to upload two:
- I select the image that I want to upload
- I create a thumbnail
- I upload both of them (and don't mind to create the progress bar just for the first one as commented)

**Comment by strausr** [comment]
Great, then taking a look at the sample photo album would be helpful to see how to upload an image and create a progress bar.

To create the thumbnail, I would suggest adding it as a preconfigured eager transformation to an upload preset. This is defined on your congif.ts.
Doing this means that when you upload your original image a transformed thumbnail version of that image will be created as well which you can later use. 

You can read more on how eager transformations work on the following link-https://cloudinary.com/documentation/upload_images#eager_transformations 

To set up the preset, navigate to your upload settings page, select edit preset. Under incoming transformation, select the crop mode to thumb along with the width and height you wish to configure.

**Comment by erperejildo** [comment]
At the moment it's working with eager transformation (https://github.com/cloudinary/cloudinary_angular/issues/144)  but I'd prefer a normal thumb and push it.

To upload the image I have this line:
```
const uploaderOptions: FileUploaderOptions = {
      url: `https://api.cloudinary.com/v1_1/${
        this.cloudinary.config().cloud_name
      }/upload`,
      isHTML5: true,
      queueLimit: 1,
      removeAfterUpload: false,
      headers: [
        {
          name: "X-Requested-With",
          value: "XMLHttpRequest"
        }
      ]
    };
```
`this.uploader = new FileUploader(uploaderOptions);`

**Comment by strausr** [comment]
You can have a separate upload preset that you use for uploading the thumbnails. You can define the thumbnails as an incoming transformation. Then all uploads using that preset will be uploaded as a thumbnail.

**Comment by erperejildo** [comment]
but this uploader preset is linked to my input, isn't? Can I have to present for the same input element?

**Comment by strausr** [comment]
Have the same preset means that when you use it to upload a resource then all uploads will have the same configuration.

**Comment by erperejildo** [comment]
hmmm, not sure if I follow you. I was using this on an old project I got it working like this:
```
Cloudinary._upload_file(thatPhoto.step3Src, {
                folder: "recipic/food",
                width: 480, height: 360
            }, function(err1, res1) {
                // now we push the thumb
                Cloudinary._upload_file(thatPhoto.step3Src, {
                    folder: "recipic/food/thumbs",
                    width: 152, height: 114,
                }, function(err2, res2) {
```

Before we were working with the local image url but now `this.uploader` has to be linked to `FileUploader`. So not sure how chain these 2 uploads (it has to be quite simple but can't see it sorry).

I'm also reading this but can't figure out how to do it:
https://cloudinary.com/documentation/angular_integration

**Comment by strausr** [comment]
To upload the image as is and as a thumbnail, you need to do two upload calls (just as you're doing above).

That being said, Uploading an image followed by uploading a low-res thumbnail of that image can be avoided when using Cloudinary.
The low-res image can either be created on the fly and cached by our servers or eagerly upon upload. This can be achieved when using an upload preset as explained above. 

Please see the following- https://support.cloudinary.com/hc/en-us/articles/202521172-Should-I-use-lazy-or-eager-transformations-

Can you please share with us the issues you faced with the integration?

**Comment by erperejildo** [comment]
The example I posted above doesn't work with Angular2+. That was on my old AngularJS app:
<img width="554" alt="screen shot 2018-07-04 at 13 42 16" src="https://user-images.githubusercontent.com/5629919/42277683-20577938-7f90-11e8-8498-41dd22d05c84.png">
The examples I saw for Angular2+ were using always the input file, not the `src`.

For me it's much easier using eager transformation, I agree, but maybe it's not the best approach for my app and my Cloudinary account:

1. I display a list of images like Instagram and I'd prefer to have just the url to display this. Don't want to depend on Cloudinary every time I want to display a image
2. I use a free account. If I need to use this service, let's say, 30 times per user (when they refresh the main view) I'll probably need to upgrade my account. I have no problem with this but I can avoid this creating the thumbnail just for the user who wants to upload an image. Let's say twice per user. 

So yes, my real question here is maybe about accounts limitations and select the option based on this:

**Option A (eager transformations):**
- Monthly transformations: 20,000 
- Bandwidth: 20GB

**Option B (thumbnail creation):**
- Total images and videos: 300,000

These are the limitations for the free account but the question would be the same for any of them.

So thinking on something similar to Instagram, which option should be better for my case?

**Comment by strausr** [comment]
Based on your use case it would be best to generate the URL eagerly or on the fly. Then you could display the image using a tag.

Regarding the account limits, once a transformation is generated it only counts once. Meaning the number of transformations does not increase per request of the resource. You can read more on how the quotas are calculated- https://support.cloudinary.com/hc/en-us/articles/203125631-How-does-Cloudinary-count-my-plan-s-quotas-and-what-does-every-quota-mean- 

If you have any other account limit specific questions- please open a ticket at support@cloudinary.com so that we can take a look at your specific usage and account.

**Comment by erperejildo** [comment]
Hmmm I see.

So in that case, if I load first my app and I see `postImage1` and `postImage2` resized to `300x300` and after me you check the same posts, does it mean that these 2 images are not going be resized again?

Makes sense because this is resized on the server. If so, this options sounds perfect to me and I wouldn't have to change anything.

**Comment by strausr** [comment]
Yes, the original will remain intact but two new derived images will be created.

**Comment by erperejildo** [comment]
Let me double check that I'm understanding you properly: you're counting 2 in total right? With 2 users checking 2 images each of them we will resize the original image for just one user because the second one sees a resized image.

Am I ok?

**Comment by strausr** [comment]
We're counting one transformation per upload so one for postImage1 and one for postImage2. Then depending on the transformation one for each- so that would be a total of 4 transformations.

**Comment by strausr** [comment]
I'm not sure I understand your implementation. You can see an example of uploading and use it as a reference on the following- https://codepen.io/team/Cloudinary/pen/QgpyOK

For more information on upload options please see- https://cloudinary.com/documentation/angular_image_and_video_upload

If you want us to take a look at your implementation, please share with us your exact code.

**Comment by erperejildo** [comment]
That example is uploading several images but in the end it's always uploading what you have selected from the gallery.

My example is this:
**Component**:
`<input type="file" accept="image/*" class="hidden" #fileInput ng2FileSelect [uploader]="imageUploadProvider.uploader" (change)="fileInput.value=''" />`

**Provider**:
load() {
    const that = this;
    const uploaderOptions: FileUploaderOptions = {
      url: `https://api.cloudinary.com/v1_1/${
        this.cloudinary.config().cloud_name
      }/upload`,
      isHTML5: true,
      queueLimit: 1,
      removeAfterUpload: false,
      headers: [
        {
          name: "X-Requested-With",
          value: "XMLHttpRequest"
        }
      ]
    };
    this.uploader = new FileUploader(uploaderOptions);

    // Add custom tag for displaying the uploaded photo in the list
    this.uploader.onBuildItemForm = (fileItem: any, form: FormData): any => {
      form.append("upload_preset", this.cloudinary.config().upload_preset);
      const tags = "recipic";
      form.append("tags", tags);
      form.append("file", fileItem);
      form.append("folder", "recipes");

      fileItem.withCredentials = false;
      return { fileItem, form };
    };

    const upsertResponse = fileItem => {
      that.zone.run(() => {});
    };

    this.uploader.onBeforeUploadItem = () => {
      // loading some spinner
    };

    this.uploader.onProgressItem = (fileItem: any, progress: any) => {
      upsertResponse({
        file: fileItem.file,
        progress
      });
      this.loading.data.content = this.getProgressBar(progress);
    };

    this.uploader.onCompleteItem = (
      item: any,
      response: string,
      status: number,
      headers: ParsedResponseHeaders
    ) => {
      const responseFormatted = JSON.parse(response);
      upsertResponse({
        file: item.file,
        status,
        data: responseFormatted
      });
      console.log("...pushed!!");

      const thumbUrl = responseFormatted.secure_url.replace(
        "upload",
        "upload/w_150"
      ); // ---> actual implementation that I need to refactor
      // pushing here to my ddbb saving both URLs
      // removing spinner
    };
  }

  getProgressBar(percentaje) {
    let html: string =
      '<div>Creating recipe...</div><progress value="' +
      percentaje +
      '" max="100"></progress>';
    return this.sanitizer.bypassSecurityTrustHtml(html);
  }

**Comment by strausr** [comment]
If you want to limit to a single upload the best approach is using our Upload Widget- https://cloudinary.com/documentation/upload_widget

Then you can set the parameter, multiple, to false which will restrict uploading multiple images.

**Comment by erperejildo** [comment]
It's already limited to 1 upload with `queueLimit: 1`. That's ok

**Comment by strausr** [comment]
I see. Let me clarify the cases- 

Let's say you upload these two images separately- this will count as 3 transformations. One for uploading the original image as is. One for taking the origin and transforming it and then another one for uploading it.

If you upload the image using an eager transformation only 2 transformations will be counted- 1 for uploading the origin and one transformation for generating the derived/transformed image.

makes sense?

**Comment by erperejildo** [comment]
Wait... to upload the image we are using transformations? Didn't know that.

But anyway, the problem with eager transformations come when we take bigger number as examples.

When you go to Instagram you'll see more post that are going to upload. 

Let's say that you push 2 images but you see 30 posts.
**With eager**: 4 + 30 transformations --> 0% more transformations on post creation, XXX% posts visits
**Without eager**: 6 + 0 transformations --> 50% more transformations on post creation, 0% posts visits

And now multiply this by 10k user

PS: of course, we'd have 50% on total images **without eager**

**Comment by erperejildo** [comment]
any ideas @strausr?

To give you another scenario, I'm using also on other parts of my app the Camera native plugin. After selecting the image from my gallery or take it with my camera I crop it. The final result is an image like this:
`this.myAvatar = "data:image/jpeg;base64," + imageData;`

both of this scenarios are not related to `ng2FileSelect `

**Comment by strausr** [comment]
You can use the example I shared above- https://codepen.io/team/Cloudinary/pen/QgpyOK
It would be a simple POST request with your file, this.myAvatar = "data:image/jpeg;base64," + imageData;

**Comment by erperejildo** [comment]
Perfect. I got it now sorry.

It was failing because I needed to make some changes:
```
handleFiles(event) {
    console.log("files: ", event.target.files[0]);
    this.uploadFile(event.target.files[0]); // call the function to upload the file
    this.uploadFile(event.target.files[0]); // call the function to upload the file
  }
```

Easy to make 2 uploads:
```
this.uploadFile(event.target.files[0]);
this.uploadFile(event.target.files[0]);
```

Question resolved. Thanks so much

PS: as an extra point, any idea which option would be better for a free account? https://github.com/cloudinary/cloudinary_angular/issues/152#issuecomment-404194037
