### ISSUE TITLE
class defined on <cl-image> also applied to the generated <img> 

### ISSUE THREAD

**Issue by johnfrades** [cloudinary/cloudinary_angular#153]
Hi, i have this issue where if i put a class in `<cl-image>`, the generated`<img>` also inherits that class which comes into a problem.

For example
`<cl-image [public-id]="someId" class="mr-3"><cl-image>`

compiles into
```
<cl-image ng-reflect-public-id="someId" class="mr-3">
 <img class="mr-3">
<cl-image>
```

the "mr-3" class is adding a right margin.
With this situation, it doubles the margin it adds because the "mr-3" class exists on both `<cl-image>` and `<img>` tags.

**Comment by strausr** [comment]
@johnfrades Can you please provide us with a live example?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
