### ISSUE TITLE
Videos not playing in chrome

### ISSUE THREAD

**Issue by gate3** [cloudinary/cloudinary_angular#154]
The videos don't seem to be playing in chrome when using the angular sdk. It plays on my ubuntu os on chromium, but doesn't play on mac

- My chrome version is Version 67.0.3396.99 (Official Build) (64-bit)
- Angular "@angular/core": "^4.0.0"
- Cloudinary angular version "@cloudinary/angular-4.x": "^1.0.0"

Has this happened to anybody or is there any solution.

**Comment by strausr** [comment]
Can you please share with us a live page where you're seeing this?

**Comment by gate3** [comment]
mysportale.com/freestyle

**Comment by strausr** [comment]
I'm unable to access the page. I'm seeing the following- "Error detected by Application Firewall. Please contact support if you have any questions."

**Comment by gate3** [comment]
Thats strange, I can access it.

![image](https://user-images.githubusercontent.com/3597437/42498987-8a1ecce2-8425-11e8-859d-8250d0586abb.png)

**Comment by gate3** [comment]
That's my point exactly, it works on every browser except the latest version of chrome.

**Comment by strausr** [comment]
The video is playing on chrome latest version-https://jsfiddle.net/eitanp461/sxvLj5qy/
It looks like the issue might be the server that's hosting the video

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
