### ISSUE TITLE
could drag multiple images but are not being uploaded

### ISSUE THREAD

**Issue by sgireddy** [cloudinary/cloudinary_angular#16]
Looks like we could drag or select multiple images but it is only uploading the latest image. can you please add support to upload multiple images? I was able to add this feature on jquery with multiple="multiple" but the same is not working for angular version. 

                <div class="form_line">
                    <label>Image:</label>
                    <div class="form_controls">
                        <div class="upload_button_holder">
                            <div href="#" class="upload_button" ng-file-select="onFileSelect($files)" data-multiple="true" multiple="multiple" title="aaaa" onclick="this.value = null">Upload</div> 
                        </div>
                        <div class="status">{{status}}</div>
                        <div class="progress-bar">
                            <div class="progress" style="width: {{progress}}%" ng-init="progress=0"></div>
                        </div>
                    </div>
                </div>

**Comment by itaibenari** [comment]
pushed an updated example with multiple uploads. see if it is useful.

**Comment by sgireddy** [comment]
cool, thank you. For the sake of completeness can you please enhance it to include both single file & multi-file upload options separately.
