### ISSUE TITLE
Lazy loaded module

### ISSUE THREAD

**Issue by erperejildo** [cloudinary/cloudinary_angular#160]
What's the best way of doing this?

I found that we need to use with `ng2-translate` `forRoot()` and `forChild()` ([more info](https://ionicframework.com/docs/developer-resources/ng2-translate/#lazy-loading-pages)).

Let's say we've got this config:
- Component1 (we need to select an image)
- Component2 (we need to upload the image)
- Component3 (nothing related to images)

**Comment by strausr** [comment]
Implementing this would be the same as #152. The upload should not be any different.

**Comment by erperejildo** [comment]
fair enough. I though we may have had a different configuration as `ngx-translate`.

Cheers
