### ISSUE TITLE
Using Video player events

### ISSUE THREAD

**Issue by monis01** [cloudinary/cloudinary_angular#162]
Hi 
How can I detect video `play`, `pause` and `ended` events as described in [cloudinary video events](https://cloudinary.com/documentation/video_player_events_analytics). What will be `cld.videoPlayer` in this case. Is `cld` cloudinary service?
Thanks

**Comment by igy** [comment]
Hi Monis,

Using the example in the video player API reference documentation, `cld` is an instance of the Cloudinary object from the JS SDK, usually initialized with the function 
`cloudinary.Cloudinary.new()`. Full documentation for that SDK can be found here: https://cloudinary.com/documentation/javascript_integration

There's a detailed example in the [video player documentation](https://cloudinary.com/documentation/video_player_events_analytics#using_video_events) which shows examples of event processing, you can find that here: https://demo.cloudinary.com/video/player.html#section02 

If you have any further questions please let us know. You can also create a ticket for our support team at https://support.cloudinary.com/hc/en-us
