### ISSUE TITLE
Delete Image is not working

### ISSUE THREAD

**Issue by crazycodewriter** [cloudinary/cloudinary_angular#166]
We are trying to remove image but when click delete image button nothing happens. Here is the code:

**Angular Service**
```
DeleteImage(imageId, imageVersion): Observable<any> {
    return this.http.delete(`${BASEURL}/delete-image/${imageId}/${imageVersion}`);
  }
```

**Angular Component**

```
 DeleteImage(image) {
    this.usersService.DeleteImage(image.imgId, image.imgVersion).subscribe(
      data => {
        this.socket.emit('refresh', {});
      },
      err => console.log(err)
    );
  }
```

**HTML**

```
<button type="submit" class=" btn btn-default submit-btn btn-upload " (click)="DeleteImage(image)">
                                    <i class="material-icons">attachment</i>
                                    Delete</button>
```

Each user image has such a button which should delete it. There is also set as profile image button with the same concept which one works perfectly unlike this one.

Also here is the backend Node.js part:

```
DeleteImage(req, res) {
    cloudinary.uploader.destroy( { imgId, imgVersion } = req.params, async result => {
      await User.update(
        {
          _id: req.user._id
        },
        {
          $pull: {
            images: {
              imgId: result.public_id,
              imgVersion: result.version
            }
          }
        }
      )
        .then(() =>
          res
            .status(HttpStatus.OK)
            .json({ message: 'Image deleted successfully' })
        )
        .catch(err =>
          res
            .status(HttpStatus.INTERNAL_SERVER_ERROR)
            .json({ message: 'Error deleting image' })
        );
    });
  },
```

```
router.delete(
  '/delete-image/:imgId/:imgVersion',
  AuthHelper.VerifyToken,
  ImageCtrl.DeleteImage
);
```

What is wrong? Why it's not deleting an image in both Angular side and backend?

**Comment by strausr** [comment]
The delete functionality your using is not Cloudinary related.

If you want to delete images you will need to use our authenticated API. Using admin API requires the account's secret key. 
It should not be used in client code since it leaks that secret.
The safer alternative would be creating a custom endpoint in your backend which calls Cloudinary's admin API for deletion (so that the secret is not exposed).- https://cloudinary.com/documentation/admin_api#delete_resources

Cloudinary also supports a time-constrained delete token, returned from the upload request, which should be used by client side deletion of assets, see https://cloudinary.com/documentation/upload_images#deleting_client_side_uploaded_images

You can see an example in the photo_album sample, see https://github.com/cloudinary/cloudinary_angular/blob/ac38ac4f1acf9a36d6cc7b244f6330aef9763d19/samples/photo_album/app/js/photo-album/photo-upload.component.ts#L121

**Comment by crazycodewriter** [comment]
@strausr  First part was confusing. I used Cloudinary api in the backend before all functions like upload set default image and DeleteImage there were implemented:

```
cloudinary.config({
  cloud_name: 'name here',
  api_key: 'api key here',
  api_secret: 'secret here'
});
```

Upload image and set default work perfectly only delete don't work. These mentioned api details were implemented in Node.js backend as recommended.

**Comment by strausr** [comment]
Can you please share with me your cloudname and are you seeing any errors? 

Also, I noticed that you're not using our v2. For example, `cloudinary.v2.uploader.destroy(public_id, options, callback);`

Is there any reason for that?

**Comment by crazycodewriter** [comment]
@strausr  Cloud name is **testamicin**
When we change into v2 it throws an error public_Id is not defined. But without v2 as was in our code it doesn't show any error. Just usual bad request 400 which appears instantly in console log when we run a local server. So this one is not connected with delete function because it even was there before writing delete function.

**Comment by strausr** [comment]
It looks like you're not supplying the correct parameters to the method. Instead of `cloudinary.uploader.destroy( { imgId, imgVersion } `
Please do the following `cloudinary.uploader.destroy(imgId)`. Note that there is no need to pass in the parameters as an object and that we don't process the version as well.

Moreover, this specific method will always return 200, what changes is the json response depending on if the image exists or not so it's not really clear what you're trying to achieve with the following-

```
async result => {
      await User.update(
        {
          _id: req.user._id
        },
        {
          $pull: {
            images: {
              imgId: result.public_id,
              imgVersion: result.version
            }
          }
        }
      )
        .then(() =>
          res
            .status(HttpStatus.OK)
            .json({ message: 'Image deleted successfully' })
        )
        .catch(err =>
          res
            .status(HttpStatus.INTERNAL_SERVER_ERROR)
            .json({ message: 'Error deleting image' })
        );
    });
  },
``` 
I would also suggest using the v2 version as it has callback functionality- 
`cloudinary.v2.uploader.destroy(public_id, options, callback);`?

**Comment by strausr** [comment]
Can you please verify that the imgId your passing is is a valid public_id? Looking into our logs it looks like you're passing in the following- `ResourceInvalid: public_id (v/) is invalid`

**Comment by crazycodewriter** [comment]
@strausr How to verify? I am logged in with that user with who uploaded that image and uploaded successfully. Now the whole code for deleting looks like this:

```
DeleteImage(req, res) {
    const  imgId  = req.params;
    cloudinary.uploader.destroy(imgId),  async result => {
      await User.update(
        {
          _id: req.user._id
        },
        {
          $pull: {
            images: {
              imgId: result.public_id,
              imgVersion: result.version
            }
          }
        }
      )
        .then(() =>
          res
            .status(HttpStatus.OK)
            .json({ message: 'Image deleted successfully' })
        )
        .catch(err =>
          res
            .status(HttpStatus.INTERNAL_SERVER_ERROR)
            .json({ message: 'Error deleting image' })
        );
    };
  },
```

```
router.delete(
  '/delete-image/:imgId/:imgVersion',
  AuthHelper.VerifyToken,
  ImageCtrl.DeleteImage
);
```
**Angular**

```
 DeleteImage(imageId, imageVersion): Observable<any> {
    return this.http.delete(`${BASEURL}/delete-image/${imageId}/${imageVersion}`);
  }
```
```
  DeleteImage(image) {
    this.usersService.DeleteImage(image.imgId, image.imgVersion).subscribe(
      data => {
        this.socket.emit('refresh', {});
      },
      err => console.log(err)
    );
  }
```

**Comment by strausr** [comment]
@crazycodewriter To delete an image you'll need to pass in the public_id of the uploaded image. Is there any way you can debug your code to see what the value of public_id you're passing into the destroy method? You can try console logging its value.

Currently, we're still seeing you passing in `v1/` as the public_id value which is invalid and therefore we're seeing the following error- `public_id (v/) is invalid`

**Comment by crazycodewriter** [comment]
I only see that error which you see but for uploading. The fun part is that it uploads an image and everything works perfectly for that upload. But in the console.log I see:
**Failed to load resource: the server responded with a status of 400 (Bad Request) http://res.cloudinary.com/testamicin/image/upload/v/**
But anyway uploading works. We have also set default function which uses image parameters from Cloudinary to update profile image it works perfectly too.
Here are their controllers:

```
UploadImage(req, res) {
    cloudinary.uploader.upload(req.body.image, async result => {
      await User.update(
        {
          _id: req.user._id
        },
        {
          $push: {
            images: {
              imgId: result.public_id,
              imgVersion: result.version
            }
          }
        }
      )
        .then(() =>
          res
            .status(HttpStatus.OK)
            .json({ message: 'Image uploaded successfully' })
        )
        .catch(err =>
          res
            .status(HttpStatus.INTERNAL_SERVER_ERROR)
            .json({ message: 'Error uploading image' })
        );
    });
  },

  async SetDefaultImage(req, res) {
    const { imgId, imgVersion } = req.params;

    await User.update(
      {
        _id: req.user._id
      },
      {
        picId: imgId,
        picVersion: imgVersion
      }
    )
      .then(() =>
        res.status(HttpStatus.OK).json({ message: 'Default image set' })
      )
      .catch(err =>
        res
          .status(HttpStatus.INTERNAL_SERVER_ERROR)
          .json({ message: 'Error occured' })
      );
  }
};

```

That is why it's very strange and annoying.  For these 2 controllers, all same parameters were used and worked as expected without any problem. The only error which I see is mentioned one which shows regularly.

**Comment by strausr** [comment]
Since I can't see the value of imgId its difficult to know what is actually being passed into the destroy method. Would it be possible to share with me a few examples of the ids you passed in?  

Moreover, I took a look into your destroy logs for the past 24 hours and I can see that 38 successful requests were made. I was unable to see any unsuccessful destroy requests. Can you further elaborate on how you're verifying the images have not been deleted?  

If you can provide more information such as timestamps and specific public ids that failed to be deleted I'd be happy to take a closer look into our logs. Otherwise, if you could provide a live example of the deletion method failing it would be extremely helpful.

**Comment by crazycodewriter** [comment]
@strausr  after some changes it finally throws this error:

**HttpErrorResponse {headers: HttpHeaders, status: 400, statusText: "Bad Request", url: "http://localhost:3000/api/chatapp/delete-image/dh6zctck0uhmy6m7sgh4/1546520357", ok: false, …}
error:
message: "Image not found"
__proto__: Object
headers: HttpHeaders
lazyInit: ƒ ()
lazyUpdate: null
normalizedNames: Map(0)
size: (...)
__proto__: Map
[[Entries]]: Array(0)
length: 0
__proto__: Object
message: "Http failure response for http://localhost:3000/api/chatapp/delete-image/dh6zctck0uhmy6m7sgh4/1546520357: 400 Bad Request"
name: "HttpErrorResponse"
ok: false
status: 400
statusText: "Bad Request"
url: "http://localhost:3000/api/chatapp/delete-image/dh6zctck0uhmy6m7sgh4/1546520357"
__proto__: HttpResponseBase
constructor: ƒ HttpErrorResponse(init)
__proto__: Object**

And here is the code:

```
async DeleteImage(req, res) {
    try {
      const {imgId } = req.params;
      cloudinary.uploader.destroy(imgId,async function(response){
        console.log("response",response)
        if(response.result == 'ok'){
          let updatedUser = await User.updateOne({
            _id: req.user._id
          }, {
            $pull: {
              images: {
                imgId: imgId,
                imgVersion: imgVersion
              }
            }
          })
          if (updatedUser) {
            res.status(HttpStatus.OK).json({
              message: 'Image deleted successfully'
            })
          } else {
            res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
              message: 'Error deleting image'
            })
          }
        }else{
          res.status(HttpStatus.BAD_REQUEST).json({
            message: 'Image not found'
          })
        }
      });
    } catch (error) {
      res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
        message: 'Error occured'
      })
    }
  },
```

```
router.delete(
  '/delete-image/:imgId/:imgVersion',
  AuthHelper.VerifyToken,
  ImageCtrl.DeleteImage
);
```

Angular part is left the same as added in the above earlier written comment.

**Comment by strausr** [comment]
Your code for the destroy method looks correct. 
The error you're seeing is not related to Cloudinary or the destroy request. Moreover, the URL is not a Cloudinary one- http://localhost:3000/api/chatapp/delete-image/dh6zctck0uhmy6m7sgh4/1546520357 

It looks like this is what is causing the error-
router.delete(
  '/delete-image/:imgId/:imgVersion'

But this is not related to the destroy request or to Cloudinary. Can you please describe what its meant to do?

Also, I have checked our logs again and I don't see any failed destroy requests in the past 7 days.

**Comment by crazycodewriter** [comment]
This URL is the router URL for API which communicates with:

**Angular**

 ```
DeleteImage(imageId, imageVersion): Observable<any> {
    return this.http.delete(`${BASEURL}/delete-image/${imageId}/${imageVersion}`);
  }
```
 ```
 DeleteImage(image) {
    this.usersService.DeleteImage(image.imgId, image.imgVersion).subscribe(
      data => {
        this.socket.emit('refresh', {});
      },
      err => console.log(err)
    );
  }
```
```
<button type="submit" class=" btn btn-default submit-btn btn-upload " (click)="DeleteImage(image)">
                                    <i class="material-icons">attachment</i>
                                    Delete</button>
```

So for deleting each image it passes  imgId and imgVersion for sending request through the Angular Observable to that mentioned URL. It's a typical connection between Angular and Node.js. What do you recommend to change with that router?

**Comment by crazycodewriter** [comment]
After restarting the computer it finally started working. Now it's deleting image but there is one bug. When we upload an image, then set that one as profile image and after some period delete that image, it deletes from our images tab and deletes from cloudinary as well but it stays as the profile image even after deleting. How does it stay there even when then that image doesn't exist in Cloudinary?

**Comment by strausr** [comment]
The image is cached. When deleting you should set invalidate to true. You can read more on invalidation on the following link- https://cloudinary.com/documentation/upload_images#invalidating_cached_media_assets_on_the_cdn
