### ISSUE TITLE
getting unauthorized error while getting list of images json 

### ISSUE THREAD

**Issue by ishtaqkhan** [cloudinary/cloudinary_angular#169]
getting unauthorized error while getting list of images json 
![image](https://user-images.githubusercontent.com/22650927/51334729-6d2bef80-1aa6-11e9-9d75-e3d0e40d664e.png)

**Comment by igy** [comment]
Hi Ishtaq,
The [client-side resource list](https://cloudinary.com/documentation/image_transformations#client_side_resource_lists) resource type is disabled by default on all accounts for security reasons.
You can fix this by opening the Security settings in your Management console and clearing the checkmark from the Resource list item under Restricted image types, then save the settings.

Please try that, and let me know if it solves the issue for you

**Comment by ishtaqkhan** [comment]
thank you very much. Appreciate your help!!  I am able to get response now.

**Comment by igy** [comment]
Great, glad to hear it!
