### ISSUE TITLE
Does the [clSrcset] directive actually work? If so, how?

### ISSUE THREAD

**Issue by BrendanBerkley** [cloudinary/cloudinary_angular#170]
Documentation was extremely light on this feature in particular. When I used it by passing in a single ID, it'd create an image with a srcset of...just that image. Just one image, but the basic functionality is there. If I tried to do something like `[clSrcset]="imageId 400w, imageId 800w"`, it would stringify that and error rather than setting up two image URLs for me.

Am I using it wrong? Is there an example of this being used in the wild somewhere?

**Comment by strausr** [comment]
Can you please share with us your implementation?

**Comment by BrendanBerkley** [comment]
I created https://github.com/BrendanBerkley/Cloudinary-Angular-clSrcset-Issue to demonstrate the problem. Relevant code is here:

```html
<h3>[clSrcset] with one source</h3>

<p>Nominally works, though a one-image srcset isn't all that useful, and I'd expect a src fallback</p>

<img clSrcset="sample" width="200"/>

<blockquote>
  &lt;img _ngcontent-c0="" clsrcset="sample" ng-reflect-cl-srcset="sample" srcset="http://res.cloudinary.com/demo/image/upload/sample" width="200"&gt;
</blockquote>

<h3>[clSrcset] attempts at multiple sources</h3>

<img clSrcset="sample 200w, sample 400w"/>
<img clSrcset="sample 2x"/>
<img clSrcset="sample.jpg 2x"/>

<p>
  These attempts generate URLs that doesn't work. I'd expect them to generate multiple image URLs.
</p>
```

**Comment by bufke** [comment]
Here is an example of how to use it

```
<img
  clSrcset="https://cloudinary.com/images/logo.png 400w, https://res.cloudinary.com/demo/image/upload/sample.jpg 600w"
  fetch-format="auto"
/>
```

Notice how you have to pass the full url (not the public id). Using the directives you can still make use of cloudinary features like auto format. This won't work with cl-image. I'm not aware of any way to make a srcset with cl-image which is too bad as that would let you pass just the public id and let cl-image find your cloud_name for you (set globally in modules)

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
