### ISSUE TITLE
about download

### ISSUE THREAD

**Issue by Orucb** [cloudinary/cloudinary_angular#172]
Hello,
is it possible to  download this sample ocr project?

**Comment by yakirp** [comment]
Hi, 
I'm not sure we have an Angular OCR sample project.
If you need any help with OCR, please try to contact us at support@cloudinary.com

Best
Yakir

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
