### ISSUE TITLE
Cannot read property 'responsive_class' of null

### ISSUE THREAD

**Issue by mrkhangtran** [cloudinary/cloudinary_angular#174]
Hi everyone,

I am getting an issue with Cloudinary on production only (ng build --prod) which works fine on development. The issue is as below

**Error**
Cannot read property 'responsive_class' of null

**Environment**
- Angular 7.2.1
- @cloudinary/angular-5.x": "1.0.2
- cloudinary-core": "2.6.2
- Angular CLI

**How I import the module**
- AppModule
![image](https://user-images.githubusercontent.com/20411087/55897359-90b88f00-5bea-11e9-9a31-512d9c3319ad.png)
![image](https://user-images.githubusercontent.com/20411087/55897380-97df9d00-5bea-11e9-937e-9f90e57caedc.png)

- Child Module
I use several Cloudinary directives in my child module's components so I have to do the same import as above in the child module

**"responsive_class" property**
I looked at the built JS file and "responsive_class" property is around these codes
![image](https://user-images.githubusercontent.com/20411087/55896437-809fb000-5be8-11e9-8880-763d5e076a26.png)

Please help advise for this case. Thank you very much.

**Comment by strausr** [comment]
@mrkhangtran can you please share with us a repo or a live implementation so that we can further investigate this?

**Comment by mrkhangtran** [comment]
hi @strausr 

Thanks for looking into this. Sorry for my late response.
I have created a repo to reproduce this at https://github.com/mrkhangtran/CloudinaryDemo

On experimenting this on a blank repo. I found out that this error happens when using the Cloudinary directive "cl-image" (I have not tried others yet)

I imported the Cloudinary and used the cl-image in SampleModule > SampleComponent

I config the default route to the SampleComponent already. Please "ng serve --prod" and the error will show up in console immediately.

**Comment by strausr** [comment]
Hi @mrkhangtran 

I couldn't find where you're importing Cloudinary. Can you please specify the path?

**Comment by mrkhangtran** [comment]
hi @strausr 

Please navigate to /src/app/main/sample/sample.module.ts

**Comment by strausr** [comment]
@mrkhangtran it like you're using an older version of cloudinary-core. Can you please update to the latest version?

**Comment by mrkhangtran** [comment]
hi @strausr 

I have updated the package cloudinary-core to latest version 2.6.3
One thing I notice is that the version inside the JS files are still 2.6.2
![image](https://user-images.githubusercontent.com/20411087/56601857-62917100-6626-11e9-97fb-6fd38657fcb5.png)

I tested again, now the 'responsive_class' error has gone, however another error shows up in console as "Unknown cloud_name" in production mode while this works in development mode

**Comment by strausr** [comment]
@mrkhangtran Please make sure that the version is actually updated. You might need to delete your node-modules. 

The error you're seeing is usually related to cloud_name being incorrect. Can you please verify that it is being imported correctly.

**Comment by mrkhangtran** [comment]
hi @strausr 

I have updated the cloudinary-core package as the "responsive_class" error does not happen anymore.
Please have a look here https://github.com/cloudinary/pkg-cloudinary-core/blob/master/cloudinary-core.js which is still 2.6.2 in the header while the version is stated to be 2.6.3

Regarding to the cloud_name, it works in development mode, with the same config being used for production mode.

**Comment by aleksandar-cloudinary** [comment]
Hi @mrkhangtran. Regarding the cloud_name error, are your other environment variables/setup the same between development and production?

**Comment by mrkhangtran** [comment]
hi @aleksandar-cloudinary ,

Thanks for looking into this. To make sure of this, I used just a single config for both development and production (without referencing environment variables)

Please check my cloudinary config
https://github.com/mrkhangtran/CloudinaryDemo/blob/master/src/app/cloudinary.config.ts

And this is where I import the config
https://github.com/mrkhangtran/CloudinaryDemo/blob/master/src/app/main/sample/sample.module.ts

**Comment by aleksandar-cloudinary** [comment]
Hi @mrkhangtran. Thanks for providing this. At first glance, the setup looks correct. Would you be able to see which cloud_name is attempted to be sent to Cloudinary? As that could narrow down where this issue is originating from. In addition, are you running this with `ng build --configuration=production`?

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
