### ISSUE TITLE
<cl-transformation [width]="'100'"/> not possible

### ISSUE THREAD

**Issue by bjornharvold** [cloudinary/cloudinary_angular#176]
Hi Team Cloudinary!

Was this a design decision? I need to create a module slideshow viewer and need to inject the width and the height into the slideshow for different use cases.

As it stands, this doesn't work. I can only hardcode the width and the height. E.g. width="100".

Thoughts?

Cheers,
Bjorn

**Comment by strausr** [comment]
@bjornharvold Can you please elaborate more on how you're injecting?

**Comment by bjornharvold** [comment]
This is how we use it now. Not possible to make those values dynamic as it stands.

```
 <cl-image [public-id]="featuredImage"
                    default_image="noimage.png"
                    secure="true"
                    class="img-fluid">
            <cl-transformation height="533" width="800" crop="fit"></cl-transformation>
            <cl-transformation gravity="center" quality="auto" fetch_format="auto"></cl-transformation>
          </cl-image>
```

**Comment by strausr** [comment]
@bjornharvold  Thanks for the clarification. I'll open a feature request to further discuss this with the team. If we decide to support this in the future, we'll update here on this thread.

**Comment by strausr** [comment]
@bjornharvold My apologies for the late reply. 
This can be resolved with accessing `[attr.width]` or `[attr.height]`. For example,

`<cl-image public-id="sample" [attr.width]="dynamicWidth"></cl-image>`

Please let me know if this works for you

**Comment by strausr** [comment]
Closing due to time elapse. Please let us know if you have any further questions
