### ISSUE TITLE
Remove dependency on jQuery

### ISSUE THREAD

**Issue by tyrw** [cloudinary/cloudinary_angular#18]
I'd love to drop this into our project, but the dependency on jQuery is a deal-killer since we're keeping things as light as possible.  

We (and I assume many others) would find it pretty valuable to have cloudinary as a standalone bower install to get up to speed more quickly.

**Comment by julianfox** [comment]
+1 same for us...

**Comment by taragano** [comment]
It's on our road-map to support a jQuery-free solution for our Angular client library.
We'll let you know of any updates.

**Comment by ArdentKid** [comment]
+1

**Comment by azachar** [comment]
+1

**Comment by websirnik** [comment]
+1

**Comment by paulogr** [comment]
+1

**Comment by xaralis** [comment]
Yes! For us, it would be perfectly possible to even live with jQuery as dependency, but the problem is with all other dependencies it introduces - blueimp-file-upload in particular. The only thing from your jQuery cloudinary-js lib used here is `cloudinary.url()` function. Please, port it... thanks.

**Comment by tinusn** [comment]
I created a version with no depency on jquery, get it here [cloudinary-angular](https://github.com/tinusn/cloudinary-angular). Please note that it does not include all directives.

**Comment by tocker** [comment]
As of version 0.2.0 the library does not depend on jQuery.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
