### ISSUE TITLE
Uploading doesn't work with angular-file-upload 3.0.4

### ISSUE THREAD

**Issue by jenyas** [cloudinary/cloudinary_angular#19]
$upload.upload Receives an error from the server saying upload_preset wasn't passed in request.

**Comment by your-coddy** [comment]
Same problem for me. I checked the request details in the console and upload_preset is there as it was set inside the code.

**Comment by your-coddy** [comment]
Just figured it out! Change the "data" key to "fields", inside the dict given for the upload function.

**Comment by dasebast** [comment]
Thanks coddy! That was so frustrating.

**Comment by tocker** [comment]
See also https://github.com/danialfarid/ng-file-upload/releases/tag/3.0.0:
>1) You should rename data to fields for $upload.upload()
The 'fields' option is added to $upload.upload() to send form data fields along with files like. This is similar to data option in the previous version.
You can still use the data option but it will be sent as a form data field with the name data to the server as one object. See the Readme file for more details.
