### ISSUE TITLE
question about porting to mean.io as a package.

### ISSUE THREAD

**Issue by kbowerma** [cloudinary/cloudinary_angular#2]
I am trying to get the sample app working as a package in the mean.io stack and I am getting the following error undefined is not a function from the following line in the controller.

    $scope.widget = $(".cloudinary_fileupload")

By default my app is loading jquery but I think I had read that you should not mix jquery syntax in angular.  Can you shed any light in this issue I am having. 

  It is working fine in the sample app but it only when I try to port this into the meanio framework I see this problem.    I think I have all the dependancies  loaded.

**Comment by tocker** [comment]
Closing due to the time past. Please feel free to reopen if you're still experiencing the problem.
