### ISSUE TITLE
XMLHttpRequest cannot load ... 

### ISSUE THREAD

**Issue by wikett** [cloudinary/cloudinary_angular#23]
Hi,
I´ve spent two days trying to use cloudinay angular in my angular project but I have always the same problem and I don't know how to solve it.

Has someone experience with this error?

```
XMLHttpRequest cannot load https://api.cloudinary.com/v1_1/djhqderwy/upload. Request header field Authorization is not allowed by Access-Control-Allow-Headers.
```

Thanks in advance

**Comment by tocker** [comment]
Hi @wikett,

You should not send the `Authorization` header field in the API.
BTW, you can see which fields are acceptable in any server by examining the `Access-Control-Allow-Headers` header in a pre-flight response ([more](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Headers)).

You can look at the [sample project](https://github.com/cloudinary/cloudinary_angular/tree/master/samples/photo_album) for code examples. 

Let us know if you solved this issue. Feel free to contact our support for any issue.

tocker

**Comment by wikett** [comment]
Thanks for all

**Comment by mikepc** [comment]
I have an authentication library (satellizer) that automatically injects the authorization header into any $http call  for my API. Do you know how I can go about removing it from the ng-file-upload call without re-doing my authentication plumbing?

**Comment by tocker** [comment]
Hi @mikepc 

To prevent satellizer.js from adding the header, add `skipAuthorization: true` to the upload parameters (see  also https://github.com/sahat/satellizer#question-how-can-i-avoid-sending-authorization-header-on-all-http-requests).

For example:

```
$upload.upload({
  url: "https://api.cloudinary.com/v1_1/cloud_name/upload",
  fields: {upload_preset: '1234abcd'},  // fields instead of data
  file: $scope.file,
  skipAuthorization: true // tell satellizer.js not to add the authorization header
}).success ...
```

**Comment by MYasirSheikh** [comment]
I am using token based Authentication for my app which adds a header. I tried the above method which does not work. Is there any other way to get through this problem
