### ISSUE TITLE
Provide Cloudinary Error

### ISSUE THREAD

**Issue by caelinsutch** [cloudinary/cloudinary_angular#232]
I'm getting the following error during AOT in Angular 8:

```
ERROR in Error during template compile of 'AppModule'
  Expression form not supported in 'provideCloudinary'
    'provideCloudinary' contains the error at app/app.module.ts(44,12).

```

**Comment by eyalktCloudinary** [comment]
Hey @caelinsutch, can you please elaborate on the steps you have taken that ended with this error? Can you share the app.module.ts file or at least line 44?
You may find this thread helpful - https://stackoverflow.com/questions/51037356/error-in-error-during-template-compile-of-appmodule

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
