### ISSUE TITLE
How i can get images from subfolders cloudinary  on angular component?

### ISSUE THREAD

**Issue by acevedo93** [cloudinary/cloudinary_angular#238]
Hello I need to show images in the frontend, all the images that I have inside a folder on cloudinary, eje( /uploads/brand/brand-test/image),  

How can I access this route from the angular component?

Thanks

**Comment by rebeccapeltz** [comment]
@acevedo93  It looks like you have opened a ticket with us, so we are going to use that channel to help with specific questions. You should have received email regarding your original ticket.
You can find documentation on our angular SDK with links to sample implementations here: https://cloudinary.com/documentation/angular_integration.

**Comment by acevedo93** [comment]
Hello the ticket was deleted? I can't find it in the support forum, could you pass me the link, or continue through this medium?

**Comment by rebeccapeltz** [comment]
The tickets created by the above questions were merged into https://cloudinary.zendesk.com/agent/tickets/98923.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
