### ISSUE TITLE
Get this error in production TypeError: Cannot read property 'CloudinaryJQuery' of null TypeError: Cannot read property 'CloudinaryJQuery' of null

### ISSUE THREAD

**Issue by MarvinBanguero** [cloudinary/cloudinary_angular#242]
![image](https://user-images.githubusercontent.com/54600240/70857330-4a72a880-1eba-11ea-9742-d72cbc3a6c99.png)
![image](https://user-images.githubusercontent.com/54600240/70857338-6d04c180-1eba-11ea-9cb2-b663fd3b0802.png)

Help me please I be worry :(

**Comment by michalkcloudinay** [comment]
Hi @MarvinBanguero please refer to this issue: https://github.com/cloudinary/cloudinary_angular/issues/92

**Comment by MarvinBanguero** [comment]
Thank you, me serve but  for angular-5.x must be export the variable config 
![image](https://user-images.githubusercontent.com/54600240/71029951-79696400-20de-11ea-9edf-4ced4327482b.png)
![image](https://user-images.githubusercontent.com/54600240/71029966-80907200-20de-11ea-9e7d-9fc83d5df60c.png)

**Comment by rebeccapeltz** [comment]
If you're having trouble with the config, make sure that you've created a config file that holds your configuration. It should be named config.ts and be in the same directory as the app.module.ts.
See this for an example of importing it at line 6
[https://github.com/cloudinary/cloudinary_angular/blob/master/samples/angular-cli-sample/src/app/app.module.ts](https://github.com/cloudinary/cloudinary_angular/blob/master/samples/angular-cli-sample/src/app/app.module.ts)
It should look like this with your cloud name and upload preset:
```
export default {
    cloud_name: 'CCCCCCC',
    upload_preset: 'UUUUUUUU'
};

```

**Comment by MarvinBanguero** [comment]
Hi Rebbeccca, thank you it's work.
