### ISSUE TITLE
Get all image resources not working in angular (Admin API)

### ISSUE THREAD

**Issue by MoAsmar** [cloudinary/cloudinary_angular#244]
I am trying to read all my image resources through one of the [Admin API](https://cloudinary.com/documentation/admin_api#get_resources)
`curl https://<API_KEY>:<API_SECRET>@api.cloudinary.com/v1_1/<cloud_name>/resources/image
`

but I couldn't get any data from angular, the cURL request is returning **unkown error**
Also I tried using ajax call but the response was unauthorized.

I need a way to list all images in JSON from angular component, I tried the below:

![image](https://user-images.githubusercontent.com/8542126/71549639-2646b980-29da-11ea-8718-4fd4433cc162.png)

**Comment by michalkcloudinay** [comment]
Hi @MoAsmar, For security reasons, you can't include your API secret in the client-side application. 
You can use [Client-side resources](https://cloudinary.com/documentation/advanced_url_delivery_options?query=json%20list%20images&c_query=Client-side%20resources#client_side_resources) to list resources from the client-side by their tags. The response is a JSON snippet containing all resources which correspond to the specified tag.

**Comment by MoAsmar** [comment]
Hi, I already tried that and getting 404 error, also isn't this a security issue and anyone with the url can access my images ?

**Comment by michalkcloudinay** [comment]
@MoAsmar In order to further assist and check the errors you are getting can you please open a ticket at support@cloudinary.com with your cloud name?

**Comment by MoAsmar** [comment]
sure thanks
