### ISSUE TITLE
Does not compile in Angular 9.0

### ISSUE THREAD

**Issue by minirobotdan** [cloudinary/cloudinary_angular#248]
Would appear the module is missing some metadata required to compile under Ivy, as per [this issue](https://github.com/angular/angular/issues/30972). 

Error during ng serve:

`ERROR in node_modules/@cloudinary/angular-5.x/src/cloudinary.module.d.ts:16:22 - error NG6002: Appears in the NgModule.imports of GlobalModule, but could not be resolved to an NgModule class`

**Comment by asisayag2** [comment]
Thanks for the feedback @minirobotdan, 
We are actively working on adapting to Angular9 and the next version will support it

**Comment by roeeba** [comment]
A new version was released yesterday, including Angular 9 support. Please let us know if you have any feedback. Thanks!

**Comment by minirobotdan** [comment]
Great, look forward to trying this out, thanks!
