### ISSUE TITLE
Cloudinary adding opacity and position properties automatically

### ISSUE THREAD

**Issue by hassanasad** [cloudinary/cloudinary_angular#257]
The package is adding the following properties to the `<img>` automatically - I am not sure why though?

```
opacity: 1;
position: unset;
```

Versions: 
Angular: 9.0.2
Cloudinary-Angular: 1.2.0-rc.0
Cloudinary-core: ^2.8.1

**Comment by strausr** [comment]
@hassanasad This is as expected and is part of our placeholder feature.

**Comment by hassanasad** [comment]
@strausr hmm - its causing some issues for me on. Is there a way to turn it off ?

**Comment by strausr** [comment]
@hassanasad Thank you for your report. This has been fixed in the latest release. Please let us know if you have any other issues
