### ISSUE TITLE
Links to sample code are broken

### ISSUE THREAD

**Issue by kresdjan** [cloudinary/cloudinary_angular#260]
From GitHub and from your documentation. All link to Angular sample code are broken. I just want to find a simple example on how to upload an image using Angular.

**Comment by strausr** [comment]
@kresdjan Thanks for the update we'll update the links to the sample code. Note that we don't have a direct upload but rather use the following- https://cloudinary.com/blog/file_upload_with_angular_or_angularjs_to_cloudinary

**Comment by strausr** [comment]
@kresdjan Thank you for your report. This has been fixed in the latest release. Please let us know if you have any other issues
