### ISSUE TITLE
How to generate og:image tags?

### ISSUE THREAD

**Issue by azachar** [cloudinary/cloudinary_angular#27]
Hello!

Is there any support for generating dynamic meta tag og:image url for facebook?

meta(property="og:image" content="image url how in angular??")

How should I get this?

Thanks,
Andrej

**Comment by tocker** [comment]
Hi @azachar,

You can use the JavaScript API to generate the image url:

```
$.cloudinary_url( public_id, ...)
```

See the [JavaScript documentation](http://cloudinary.com/documentation/jquery_integration) for more details.

**Comment by azachar** [comment]
Thanks! Please provide more typical examples in your angular project. Just couple of typical usage. To find this I spent some time... But anyway thank you for your reply.
