### ISSUE TITLE
Cloudinary Angular-5.x is not Angular 9 compatible

### ISSUE THREAD

**Issue by hassanasad** [cloudinary/cloudinary_angular#272]
Even though the release notes of 1.2.2 say that its Angular 9 compatible - i am getting following error when updating my Angular project.

```
Package "@cloudinary/angular-5.x" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0" (extended), would install "9.1.1").
Package "@cloudinary/angular-5.x" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0" (extended), would install "9.1.1").
```

**Comment by aditimadan-Cloudinary** [comment]
For reference: https://codesandbox.io/s/cloudinary-angular-media-library-ofmex . This one is using Angular 10 and it is compatible with the cloudinary libs. Can you please try using the same versions and test.

**Comment by hassanasad** [comment]
I believe you can replicate this issue by running:
`ng update @angular/cli @angular/core` command. It will throw the errors i mentioned above.

**Comment by strausr** [comment]
@hadarbj Thanks for the information. For future reference,  please note that we have an error template where you can specify more information when opening such issues. 

The issue which you are describing is related to ng-update. In the meantime, can you please try using npm install to update  @angular/cli @angular/core ?

**Comment by hassanasad** [comment]
@strausr Sure.
Yes with NPM install it works. However each time we update Angular we use the ng-update because of any migrations etc that might be required with it. I believe this issue can be resolved by declaring the Angular version strings as a range maybe.

**Comment by hassanasad** [comment]
Some libraries do it like this:
```
"peerDependencies": {
    "@angular/common": ">=7.0.0",
    "@angular/core": ">=7.0.0"
  },
```

Perhaps you can see this for reference: https://github.com/valor-software/ngx-bootstrap/blob/development/package.json

**Comment by strausr** [comment]
@hassanasad Thanks for the advice and feedback:) we'll discuss this internally and update here if we decide to change anything

**Comment by bjornharvold** [comment]
Yes, please bump peer dependency to Angular 10. Have to --force an "ng update" which shouldn't be necessary.

**Comment by strausr** [comment]
@bjornharvold will be handled in the next release

**Comment by abbasogaji** [comment]
@aditimadan-Cloudinary  Cloudinary module is not compatible with angular 9+, the angular cloudinary library doesnt return ModuleWithProviders  with a generic type. 

"Angular version 9 deprecates use of ModuleWithProviders without an explicitly generic type, where the generic type refers to the type of the NgModule. In a future version of Angular, the generic will no longer be optional."

Currently can't use Cloudinary on Angular 10

**Comment by eyalktCloudinary** [comment]
@abbasogaji thank you for your feedback! 
Note that the Cloudinary module does return ModuleWithProviders with a generic type -
https://github.com/cloudinary/cloudinary_angular/blob/master/projects/angular-cld/src/lib/cloudinary.module.ts#L61
> ModuleWithProviders\<CloudinaryModule\>

Can you please recreate the issue, and elaborate on where are you seeing different behavior?
Is your version of the Cloudinary module up to date?

**Comment by abbasogaji** [comment]
I guess i installed the older version, let me try with the newer version

**Comment by abbasogaji** [comment]
@eyalktCloudinary @aditimadan-Cloudinary   it works fine (v1.3.1) on Angular 10

**Comment by eyalktCloudinary** [comment]
@abbasogaji Glad to hear it's working!
