### ISSUE TITLE
cluoudinary in ionic framework

### ISSUE THREAD

**Issue by LearningTools** [cloudinary/cloudinary_angular#28]
as would be the process for using ionic framework and upload the image, Greetings

**Comment by tocker** [comment]
Hi @LearningTools,

I have not tried it yet myself, but @calendee posted a gist that seems to do the job: [imageUploadService.js](https://gist.github.com/calendee/20e344a8152ff76cbe6f).

**Comment by LearningTools** [comment]
o.k gracias , casi no entiendo el servicio :p

**Comment by tocker** [comment]
Sure!

Please feel free to contact us for any other issue.

**Comment by robksawyer** [comment]
Doesn't seem to be working for me in Ionic. However, it works fine in the browser via `ionic serve`. But, when you get it to the device, something is failing. Any ideas?

**Comment by robksawyer** [comment]
After some debugging (via Safari), I found that when using `cl-image`, the protocol is transformed to `file://` when running on the emulator and very likely on the actual device. Any idea how to fix it?

Have an open question on StackOverflow, as well. See http://stackoverflow.com/questions/32686054/cloudinary-images-not-working-via-ionic-framework.

<img width="965" alt="screen shot 2015-09-21 at 12 47 11 am" src="https://cloud.githubusercontent.com/assets/179419/9987517/69bf2c02-5ffd-11e5-8fe9-ac38fec4ddfc.png">
