### ISSUE TITLE
I'm getting Cross-Origin Request Blocked error since 2 weeks

### ISSUE THREAD

**Issue by burakkilic** [cloudinary/cloudinary_angular#29]
Hi;

I was successfully using the library. But since 2 weeks, I started to get CORS error. What is the proper way to fix that?

UPDATE: In Chrome, I am getting following:

    Request header field Authorization is not allowed by Access-Control-Allow-Headers

**Comment by tocker** [comment]
Hi @burakkilic,

Which server is returning the message? Can you provide more details, such as the request and response headers?

**Comment by burakkilic** [comment]
![screen shot 2015-05-14 at 11 48 10](https://cloud.githubusercontent.com/assets/123382/7628704/2fe3d6f6-fa2f-11e4-9745-df206b207cc3.png)
![screen shot 2015-05-14 at 11 48 21](https://cloud.githubusercontent.com/assets/123382/7628705/2ffe8672-fa2f-11e4-9b19-d6e4303be9e0.png)

**Comment by tocker** [comment]
You should not send the `Authorization` header field in the API.
BTW, you can see which fields are acceptable in any server by examining the `Access-Control-Allow-Headers` header in a pre-flight response ([more](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Headers)).

You can look at the [sample project](https://github.com/cloudinary/cloudinary_angular/tree/master/samples/photo_album) for code examples. 

Let us know if you solved this issue. Feel free to contact our support for any issue.

tocker

**Comment by burakkilic** [comment]
But I do not send the Authorization header. Also it is not seen in the screenshots above. 

I also added 

    headers: {
                    'Authorization': undefined
                }

to my request but nothing has changed.

**Comment by tocker** [comment]
Hi @burakkilic,

Sorry for the delay in my response.

I was referring to the **Access-Control-Request_header** in your screenshot.
![2fe3d6f6-fa2f-11e4-9745-df206b207cc3](https://cloud.githubusercontent.com/assets/346642/8850127/fb5f5c24-314d-11e5-9a9a-d57681a585c6.png)

Can you please share the environment you are using (name and version numbers of components)?

**Comment by ronnpang1** [comment]
I had this issue too.
As Tocker stated, you're sending an authorization header to the api. In my project I had an interceptor that was sending an authorization token with every request with the angular-jwt library.

I managed to get rid of this error by adding:
upload.upload{
....
skipAuthorization: true
}
in the upload function. This will prevent the authentication request from being sent with the headers.

**Comment by spacepang** [comment]
I had this issue too.
As Tocker stated, you're sending an authorization header to the api. In my project I had an interceptor that was sending an authorization token with every request with the angular-jwt library.

I managed to get rid of this error by adding:
upload.upload({
....
skipAuthorization: true
})
in the upload function. This will prevent the authentication request from being sent with the headers.

**Comment by tocker** [comment]
@spacepang - thanks for the tip. It only applies to angular-jwt unfortunately.
Angular and the Cloudinary SDK are not adding this header, so the culprit must be some code in between.

**Comment by tocker** [comment]
@burakkilic I found that other libraries are adding the Authorization header to the request. One such library is [Satellizer.js](https://github.com/sahat/satellizer).

@spacepang's suggestion (skipAuthorization) works for satellizer too.

If you are still experiencing this issue, verify that other scripts are not modifying the request. (In Angular this is normally done using $httpProvider.interceptors.)

I'm closing this ticket as it is not a cloudinary_angular issue. However please feel free to open an issue here or at http://support.cloudinary.com/hc/en-us if you still have a problem.

I'd appreciate it if you drop a note here if you manage to solve the issue too!

**Comment by sunabozu** [comment]
@spacepang Thanks man, you saved me a lot of time!

**Comment by narutosanjiv** [comment]
@spacepang  Thanks man, You saved me too.

**Comment by NIYAZ04** [comment]
const [images, setImages] = useState([]);

  useEffect(() => {
    const fetchImages = async () => {
      try {
        const response = await axios.get(`https://api.cloudinary.com/v1_1/${import.meta.env.VITE_CLOUDINARY_NAME}/resources/image`, {
          headers: {
            Authorization: `Basic ${btoa(import.meta.env.VITE_CLOUDINARY_KEY + ':' + import.meta.env.VITE_CLOUDINARY_SECRET)}`
          }
        });
        setImages(response.data.resources);
      } catch (error) {
        console.error("Error fetching images from Cloudinary:", error);
      }
    };

    fetchImages();
  }, []);
  
  "
  
  I am also facing CORS error

**Comment by dannyv-cloudinary** [comment]
Hi @NIYAZ04. As mentioned above, you shouldn't send an Authorization header in your request. Could you please remove it and let us know how it goes?
