### ISSUE TITLE
Handling 404 images

### ISSUE THREAD

**Issue by chris480** [cloudinary/cloudinary_angular#296]
## Explain your use case
Some user submitted images inevitably disappear for one reason or another. Having the ability to handle a 404 (error) would be beneficial to controlling the end ux.

## Describe the problem you’re trying to solve
I want to add an error handler to the <cl-image> component

## Do you have a proposed solution?
Passing an error handler event to the component or the <img> tag generated
```
<cl-image ... (error)="doSomething($event)">

**Comment by roeeba** [comment]
Thank you for your suggestion, @chris480. We'll update here once the team reviews it.

**Comment by strausr** [comment]
@chris480 We apologize for the late response. The native approach to this is using an `onerror` event 

`<cl-image ... (onError)="doSomething($event)">
`
