### ISSUE TITLE
SSR Lazy Load Directive Bug

### ISSUE THREAD

**Issue by bclynch** [cloudinary/cloudinary_angular#299]
## Describe the bug in a sentence or two.

When using the loading="lazy" directive with SSR / Angular universal there are window is not defined errors. Checking if it exists [here](https://github.com/cloudinary/cloudinary_angular/blob/dc438c2c792dc1371e35fa345b2a526c30be60b3/projects/angular-cld/src/lib/cloudinary-lazy-load.directive.ts#L25-L27) might fix it?

## Issue Type (Can be multiple)

[x] UI/Performance - Display or performance issues
[x] Behaviour - Functions aren’t working as expected (Such as generate URL)

## Steps to reproduce
```
<cl-image crop="fit" [public-id]="slide.image" type="fetch" loading="lazy" width="auto" responsive
  [attr.alt]="'Carousel Image ' + i">
  <cl-placeholder type="blur"></cl-placeholder>
  <cl-transformation quality="auto" fetch-format="auto"></cl-transformation>
</cl-image>
```

## Error screenshots 
<img width="891" alt="Screen Shot 2021-01-04 at 7 48 41 PM" src="https://user-images.githubusercontent.com/15255973/103604489-1fdcfe80-4ec6-11eb-80c0-b734f250ff1e.png">

## Versions and Libraries (fill in the version numbers)
Angular Cloudinary SDK - 1.3.3 
Angular - 11.x.0
Node - 14.15.3
NPM - 6.14.9

**Comment by Vdeub-cloudinary** [comment]
Hi @bclynch, could you share a sample code like Codesandbox in order to reproduce the issue? 
I tried to use an SSR Angular project from Codesandbox and adding Cloudinary which seems to work fine so I would like to be sure that I am in the same condition as you are.

**Comment by ddotx** [comment]
> Hi @bclynch, could you share a sample code like Codesandbox in order to reproduce the issue?
> I tried to use an SSR Angular project from Codesandbox and adding Cloudinary which seems to work fine so I would like to be sure that I am in the same condition as you are.

what is your angular version?

I'm also face this problem

**Comment by martinsotirov** [comment]
I have the same problem on my server side rendered Angular 11 app.
```
ERROR TypeError: Cannot read property 'src' of undefined
```

**Comment by d-mendoza** [comment]
@ddotx @martinsotirov could you share a sample code like Codesandbox in order to reproduce the issue?
I tried to use an SSR Angular project from Codesandbox and adding Cloudinary which seems to work fine so I would like to be sure that I am in the same condition as you are.

**Comment by martinsotirov** [comment]
@d-mendoza, I'll see if I can extract a minimal example from our codebase.

Btw, I don't have an error with `window` missing like @bclynch because I'm injecting a window mock with [domino](https://www.npmjs.com/package/domino) in my `server.ts`.

My specific error with cloudinary and SSR is:

```
ERROR TypeError: Cannot read property 'src' of undefined
    at LazyLoadDirective.loadImage (/my/project/path/dist/my-app/server/vendors~home-home-module~vendors-vendors-module.js:9385:49)
    at LazyLoadDirective.ngAfterViewInit (/my/project/path/dist/my-app/server/vendors~home-home-module~vendors-vendors-module.js:9374:18)
    at callHook (/my/project/path/dist/my-app/server/main.js:63948:18)
    at callHooks (/my/project/path/dist/my-app/server/main.js:63919:17)
    at executeInitAndCheckHooks (/my/project/path/dist/my-app/server/main.js:63870:9)
    at refreshView (/my/project/path/dist/my-app/server/main.js:70912:21)
    at refreshEmbeddedViews (/my/project/path/dist/my-app/server/main.js:71961:17)
    at refreshView (/my/project/path/dist/my-app/server/main.js:70865:9)
    at refreshEmbeddedViews (/my/project/path/dist/my-app/server/main.js:71961:17)
    at refreshView (/my/project/path/dist/my-app/server/main.js:70865:9)

```

**Comment by r3plica** [comment]
> Hi @bclynch, could you share a sample code like Codesandbox in order to reproduce the issue?
> I tried to use an SSR Angular project from Codesandbox and adding Cloudinary which seems to work fine so I would like to be sure that I am in the same condition as you are.

Hi, I also have this issue. It's directly related to the lazy directive. In the cloudinary.service.ts there is this method:

```
const isBrowser = function (): boolean {
  return typeof window !== 'undefined';
}
```

In the cloudinary-lazy-load.directive.ts the error is thrown here:

```
  isLazyLoadSupported() {
    return window && "IntersectionObserver" in window;
  }
```

it states that window is not defined, but I propose that if you copy the method from the service, you could do something like this:

```
  isLazyLoadSupported() {
    return this.isBrowser && window && "IntersectionObserver" in window;
  }

  isBrowser(): boolean {
    return typeof window !== "undefined";
  }
```

**Comment by r3plica** [comment]
Oh, and to reproduce this issue, just create a new angular project, add angular universal and cloudinary. Then when you add your image, do it like this:

```
<cl-image [public-id]="publicId"  loading="lazy">
```

If you build your project with `npm run build:ssr` and then serve it with `npm run serve:ssr` you will reproduce the error.

**Comment by strausr** [comment]
This issue has been resolve with the latest release (1.4.1). Please let us know if you're still experiencing this issue.
