### ISSUE TITLE
Any support video uploads?

### ISSUE THREAD

**Issue by burakkilic** [cloudinary/cloudinary_angular#30]
Hi;

I heard that cloudinary now supports video uploads. Is there any plan to support it?

**Comment by taragano** [comment]
It's on our road map to detach jQuery from our Angular library, including adding video support.
In the meantime, you can use our jQuery library to build video tags and URLs

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
