### ISSUE TITLE
Update Cloudinary Service Configuration during runtime

### ISSUE THREAD

**Issue by pekevski** [cloudinary/cloudinary_angular#301]
## Feature request for Cloudinary Angular SDK
An api on the cloudinary service to update the configuration during runtime

## Explain your use case
We have implemented app configuration during runtime. 

In order to initialise the config data of the cloudinary module we need to be able to update the configuration at a later stage of the angular module initialisation process.

## Describe the problem you’re trying to solve
Currently we hook into the [APP_INITIALIZER](https://angular.io/api/core/APP_INITIALIZER) provider which fetches local configuration at runtime. We would like to use the local cloudinary values and inject them into the cloudinary service that would have already been imported prior to this process. 

## Do you have a proposed solution?
add an `updateConfig(config: CloudinaryConfiguration)` method to the cloudinary.service.ts file which will update the cloudinary instances' config at that point.

**Comment by pekevski** [comment]
I now realise I can update the Cloudinary service cloudinaryInstance with:

```
this.cloudinaryService.cloudinaryInstance.config({config} as CloudinaryConfiguration);
```
Would it still be worth the introduction of an api at the angular service layer that simply performs this?
I am happy to do the pull request if so.

**Comment by eyalktCloudinary** [comment]
@pekevski Hey, thanks for reaching out!
Could you please elaborate on the use case? What configuration parameters would you want to update?
Why couldn't you configure those in app.module.ts (see [this section](https://cloudinary.com/documentation/angular_integration#config_params))?

**Comment by pekevski** [comment]
Hey! Just to clarify, the ng app follows this runtime configuration approach at start up [blog example](https://labs.thisdot.co/blog/runtime-environment-configuration-with-angular). I could be wrong but I believe that the imports of the app.module.ts are called before the APP_INITIALIZER hook therefore we don't have our cloudinary credentials at the time of `CloudinaryModule.forRoot()`. 

I can work around this by setting the config on the js cloudinary instance of the Cloudinary service after the app init hook in my `AppConfigService`, however it took me some time to dig through both the angular and core repos to realise this. 

Perhaps the angular repo could benefit by having an api to update the config to quicken the process?

**Comment by eyalktCloudinary** [comment]
@pekevski Thanks for the clarifiaction - This is planned to be supported in v2 of the Angular SDK which is in a beta phase at the moment. I'll update this thread when it is officially released.

**Comment by pekevski** [comment]
The update sounds good! I did start a branch that simply took a CloudinaryConfiguration object and updated the JS cloudinary instances' config if you would like me to push that?

Not sure if specific parameters only need updating, it could be flexible enough for any attribute in cloudinaryconfiguration to be applied?

**Comment by eyalktCloudinary** [comment]
You can add a pull request for our dev team to consider, thanks! (cc @strausr) 
We plan on making it flexible enough to change any attribute of CloudinaryConfiguration.

**Comment by strausr** [comment]
Please find the latest release
