### ISSUE TITLE
Upload singed photos with eager transformation 

### ISSUE THREAD

**Issue by franciscocobas** [cloudinary/cloudinary_angular#31]
I need to upload an image with an eager transformation. So by Cloudinary restriction I need to create a singed upload. 

The following code is what I did, but it is not working... Anyone can help me?

    cloudinary.uploadImage = function (file) {
        var deferred = $q.defer();
        var timestamp = (new Date).getTime() / 1000; // in seconds
        var signature = serverAPI.getHashSignature();

        $upload.upload({
            url: "https://api.cloudinary.com/v1_1/" + $.cloudinary.config().cloud_name + "/upload",
            data: {
                api_key: apiKey,
                timestamp: timestamp,
                signature: signature,
                tags: 'temp_cover'
            },
            file: file,
            eager: {
                width: 1920,
                height: 1080,
                crop: 'limit'
            }
        }).progress(function (e) {

        }).success(function (data, status, headers, config) {
            console.log(config)
            deferred.resolve(data);
        }).error(function (error) {
            deferred.reject(error);
        });
        return deferred.promise;
    }

The image is uploaded properly but the transformation doesn't work..

**Comment by taragano** [comment]
Hi,

Please note that:

1. `eager` should be in `data` - as the eager transformations are processed on the server.
2. Note that Eager transformations tells Cloudinary to upload the original image as is and eagerly generate additional versions of the image (transformed). If you need to transform the original, you should use an Incoming Transformation, which transforms the image before storing it in your account.
3. When given like that, it needs to be `eager: 'c_limit,w_1920,h_1080'`.
4. You should also make sure to sign that as well (either eager or incoming).

Let me know if this helps?

**Comment by franciscocobas** [comment]
Hi yes, it helped me, thanks a lot! and you are right about using "transformation" param.

here is the final working code...

    cloudinary.uploadImage = function (file) {
        var deferred = $q.defer();
        var timestamp = (new Date).getTime() / 1000, // in seconds
            max_width = '1920', //in pixels
            max_height = '1080', //in pixels
            transformation_parameter = 'w_'+max_width+',h_'+max_height+',c_limit',
            tags = 'temp_cover',
            signature = serverAPI.getHashSignature();

        $upload.upload({
            url: "https://api.cloudinary.com/v1_1/" + $.cloudinary.config().cloud_name + "/image/upload?transformation=" + transformation_parameter,
            data: {
                api_key: apiKey,
                timestamp: timestamp,
                signature: signature,
                tags: tags
            },
            file: file
        }).progress(function (e) {

        }).success(function (data, status, headers, config) {
            deferred.resolve(data);
        }).error(function (error) {
            deferred.reject(error);
        });
        return deferred.promise;
    }
