### ISSUE TITLE
Angular 13 / 14 support

### ISSUE THREAD

**Issue by skelesp** [cloudinary/cloudinary_angular#312]
Can you update the package so it is compatible with angular 13?

**Comment by leptians** [comment]
We currently do not support Angular 13. However I have pass this message to our SDK team

**Comment by skelesp** [comment]
@leptians : any progress on this one? Is your SDK team working on this issue?

**Comment by belowthewing** [comment]
@skelesp although we do not currently support Angular 13, we may add this in the future. I will let you know if / when that happens.

**Comment by momoip** [comment]
@volago I'm checking with our SDK team and will keep you posted.

**Comment by bjornharvold** [comment]
Now that Angular 14 is out, bump that another +1.

**Comment by michalkcloudinay** [comment]
Hi @bjornharvold and @volago, 
The new Angular SDK is compatible with both Angular 13 and 14. You can find the latest package here: https://github.com/cloudinary/frontend-frameworks/tree/master/packages/angular
If you have any issues with configuring the SDK please let us know.
Thanks

**Comment by indraraj26** [comment]
I was trying to reproduce this issue [149](https://github.com/cloudinary/frontend-frameworks/issues/149) but in stackblitz, I am having error that 'CloudinaryModule' does not appear to be an NgModule class.

[stackblitz](https://stackblitz.com/edit/angular-ivy-eee3nf?file=src%2Fapp%2Fcloudinary-image.pipe.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fhello.component.ts)

**Comment by michalkcloudinay** [comment]
Hi @volago,

Yes, we indeed have a warning. That being said, this does not prevent or cause any errors when using angular 13/14. We will take care of this warning internally. 

Please let us know if you have any issues.
Thanks

**Comment by volago** [comment]
Hi,

as I mentioned earlier, there was a warning.
In may 2023 it will turn into breaking change.

https://github.com/angular/angular/releases
Please get rid of View Engine and be prepared to Angular v16

Thanks

**Comment by dannyv-cloudinary** [comment]
Hi @volago. Danny from the Developer Support Team here.

We've spoken to our dev team internally and this is already on our roadmap to address in a future release before the deprecation deadline. There should be no production impact by the time May 2023 comes around.
If you have any further queries, you're welcome to drop a comment here or raise a support ticket with us via https://support.cloudinary.com/hc/en-us/requests/new

Many thanks,
-Danny
