### ISSUE TITLE
@cloudinary/angular-5.x not compatible with Angular Ivy

### ISSUE THREAD

**Issue by hirenmistry17** [cloudinary/cloudinary_angular#321]
## Bug report for Cloudinary Angular SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
installed package( "@cloudinary/angular-5.x": "^1.5.3"), after installing when we are trying to import 'CloudinaryModule', getting error that this package does not compatible with angular Ivy and Check if a newer version of the library is available...
added screenshot below
…

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] UI/Performance - Display or performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types
[ ] Other (Specify)
 

## Error screenshots 
… <img width="536" alt="image" src="https://github.com/cloudinary/cloudinary_angular/assets/50474523/f5c5b10e-d18a-4e58-b442-41c87d084452"> 

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[ ] All

## Versions and Libraries (fill in the version numbers)
"@cloudinary/angular-5.x": "^1.5.3",
Angular - 16.2.0
Node - 18.16.0
NPM - 9.5.1

## Config Files (Please paste the following files if possible)
Package.json :
 "dependencies": {
    "@angular/animations": "^16.2.0",
    "@angular/common": "^16.2.0",
    "@angular/compiler": "^16.2.0",
    "@angular/core": "^16.2.0",
    "@angular/forms": "^16.2.0",
    "@angular/material": "^16.2.6",
    "@angular/platform-browser": "^16.2.0",
    "@angular/platform-browser-dynamic": "^16.2.0",
    "@angular/router": "^16.2.0",
    "@cloudinary/angular-5.x": "^1.5.3",
    "@kolkov/angular-editor": "^2.0.0",
    "@ng-bootstrap/ng-bootstrap": "^8.0.4",
    "@ng-idle/core": "^13.0.0",
    "@ng-idle/keepalive": "^13.0.0",
    "@o.krucheniuk/ngx-signature-pad": "^0.0.7",
    "async": "^3.2.4",
    "babel-polyfill": "^6.26.0",
    "bootstrap": "^4.6.1",
    "bootstrap-material-design": "^4.1.3",
    "bootstrap-notify": "^3.1.3",
    "cloudinary": "^1.28.1",
    "cloudinary-core": "^2.11.3",
    "concurrently": "^8.2.1",
    "cors": "^2.8.5",
    "dotenv": "^16.3.1",
    "express": "^4.18.2",
    "express-async-handler": "^1.2.0",
    "helmet": "^7.0.0",
    "joi": "^17.9.2",
    "jquery": "^3.7.0",
    "jsonwebtoken": "^9.0.2",
    "moment": "^2.29.4",
    "mongoose": "^7.4.1",
    "mongoose-autopopulate": "^1.0.1",
    "mongoose-bcrypt": "^1.11.0",
    "morgan": "^1.10.0",
    "ng2-file-upload": "^5.0.0",
    "perfect-scrollbar": "^1.5.5",
    "popper.js": "^1.16.1",
    "rxjs": "~7.8.0",
    "sweetalert2": "^11.7.28",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.1",
    "@angular/cli": "~16.2.1",
    "@angular/compiler-cli": "^16.2.0",
    "@types/jasmine": "~4.3.0",
    "babel-plugin-syntax-async-functions": "^6.13.0",
    "babel-plugin-transform-es2015-destructuring": "^6.23.0",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-register": "^6.26.0",
    "es2017": "^0.0.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "nodemon": "^3.0.1",
    "typescript": "~5.1.3"
  }

## Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by momoip** [comment]
Hi hirenmistry17,
Please note that this SDK version is not compatible with Angular 16.  This is a legacy SDK and the error is correct.

**Comment by hirenmistry17** [comment]
Hi @momoip
thanks for letting me know,
can you please inform me till which angular version, this SDK version is compatible

**Comment by dannyv-cloudinary** [comment]
Hi @hirenmistry17.

This SDK works with up to Angular 15, and our newer SDK works with version 12 upwards. Please see [this compatibility table](https://www.npmjs.com/package/@cloudinary/ng#version-support) for the new SDK.

**Comment by hirenmistry17** [comment]
![image](https://github.com/cloudinary/cloudinary_angular/assets/50474523/00f48fa6-c743-444c-bd5d-8e9145ea4374)

as you we can see here, it is not supporting upload file,
so can you please guide for uploading file in clodinary  for this npm (@cloudinary/ng)

**Comment by skalahasti-cloudinary** [comment]
Hi @hirenmistry17 ,

Thanks for your response. 
Have you tried using the samples app from the SDK code: https://github.com/cloudinary/cloudinary_angular/tree/master/projects/angular-cld/samples ?

Thanks,
Sree

**Comment by skalahasti-cloudinary** [comment]
Hi @hirenmistry17 ,

Thanks for your response. 
Have you tried using the samples app from the SDK code: https://github.com/cloudinary/cloudinary_angular/tree/master/projects/angular-cld/samples ?

Thanks,
Sree
