### ISSUE TITLE
Sample not working in ie9

### ISSUE THREAD

**Issue by ianforsyth** [cloudinary/cloudinary_angular#33]
I'm trying to get angular and cloudinary uploads to work in ie9 but haven't been able to yet. After opening a ticket with cloudinary they sent me to this repo. I have the sample project working in all browsers and ie10 but in ie9 when I click on the link to upload angular files the page is mostly blank.
![ie9_-_win7__clean___running_](https://cloud.githubusercontent.com/assets/4276285/8576784/6ba074ce-2572-11e5-87b8-9c4b7d39fa40.png)

Is this a known issue? Any way to get it working properly? Thanks!

**Comment by idobarnoam** [comment]
@ianforsyth I see that the reply id from a while back.
Is the issue still relevant?

**Comment by ianforsyth** [comment]
I'm not sure, but we're not longer supporting ie9 so it's not an issue for us.

**Comment by idobarnoam** [comment]
@ianforsyth 
Thanks for the update.
we are closing the issue.
