### ISSUE TITLE
can you upload cloudinary angular itself

### ISSUE THREAD

**Issue by kruny1001** [cloudinary/cloudinary_angular#36]
cloudinary angular have dependency cloudinary js and cloudinary. and also it has https://github.com/blueimp/jQuery-File-Upload dependency. My automation task by grunt generates huge dependency lists from your dependency setting can you upload individually?

**Comment by tocker** [comment]
We are releasing soon a new version of [cloudinary_js](https://github.com/cloudinary/cloudinary_js) that has a jQuery- and Blueimp- free core library.
