### ISSUE TITLE
Can we use it for Facebook meta image tag ?

### ISSUE THREAD

**Issue by benjaminch** [cloudinary/cloudinary_angular#37]
Hello there, 

First of all, thanks a lot for this awesome repo :) 
I am wondering if we can use cloudinary_angular to generate Facebook Image Meta header (meta tag rather than img one)?

Here's an example from the Facebook dev documentation : 

``` html
<meta property="og:image"
content="http://graphics.myfavnews.com/images/logo-100x100.jpg" />
```

Do you think we can generate such output with this package?

Thanks,
Benjamin

**Comment by tocker** [comment]
Hi @BenjaminCh ,

Thanks for the pull request and sorry for the delay. See my comment in your pull request.
I think it would be easier to simply use `cloudinary.url` to generate the content. As far as I understand this field is not dynamic so there is no need to monitor it.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
