### ISSUE TITLE
How to replace with an upload image?

### ISSUE THREAD

**Issue by Tyvain** [cloudinary/cloudinary_angular#4]
Hi,

I replace the code in the directive to have an upload image (in angular.cloudinary.js) like this (it works perfectly):
 template : '<div class="fileUpload btn btn-primary"><span>Ajouter une image</span><input name="file" type="file" class="upload" data-cloudinary-field="image_id"/> </div>',

The problem is that my lib directory in not versionned so I don't know how to have it saved. (I don't want to version external lib, as I use bower to retrieve them)

Maybe there is another way to do it?

Or should I fork the project (which I would like to avoid) ?

**Comment by tocker** [comment]
Hi @Tyvain,
If this is still an issue, can you please provide more details and explain what you are trying to do?
