### ISSUE TITLE
how to use secure url by using cl-image directive? 

### ISSUE THREAD

**Issue by kruny1001** [cloudinary/cloudinary_angular#41]
I need to have a https url. I have look through the code and it seems there is no option for secure version of image url/

**Comment by taragano** [comment]
Sorry for my response delay.

You can set the `secure` parameter to `true`, e.g.,:

```html
<cl-image public-id="{{photo.public_id}}" secure="true" format="jpg"/>
```

**Comment by taragano** [comment]
@kruny1001 - Just wanted to check whether my last response helped with answering your question.
As it's been a while since the last response, I'll close this issue now, but please feel free to re-open it if you need any further assistance.

Thanks
