### ISSUE TITLE
Round height and width values before sending to cloudinary

### ISSUE THREAD

**Issue by ericyliu** [cloudinary/cloudinary_angular#43]
Cloudinary does not accept decimal height and width values, so the cl-transformation directive should round any input before sending them off

**Comment by taragano** [comment]
Sorry for my response delay.

Something like the following should work, can you please let me know if it works for you?

```html
<cl-image public-id="{{photo.public_id}}" class="thumbnail inline" width="0.5" height="0.3" crop="fit" quality="80" format="jpg"/>
```

**Comment by taragano** [comment]
@ericyliu - Just wanted to check whether my last response helped with answering your question.
As it's been a while since the last response, I'll close this issue now, but please feel free to re-open it if you need any further assistance.

Thanks
