### ISSUE TITLE
Support for named transformations

### ISSUE THREAD

**Issue by ajsharp** [cloudinary/cloudinary_angular#44]

**Comment by taragano** [comment]
Sorry for my response delay.

Named transformations are actually already supported.
Here's an example:

```html
<cl-image public-id="{{photo.public_id}}" class="thumbnail inline" transformation="mythumbnail" format="jpg"/>
```

**Comment by taragano** [comment]
@ajsharp - Just wanted to check whether my last response helped with answering your question.
As it's been a while since the last response, I'll close this issue now, but please feel free to re-open it if you need any further assistance.

Thanks
