### ISSUE TITLE
I get: General Error, when update to last version on ng-file-upload 11.1.1

### ISSUE THREAD

**Issue by romelgomez** [cloudinary/cloudinary_angular#48]
Hi, 

With the last version of https://github.com/danialfarid/ng-file-upload, (11.1.1) , i get 

{"error":{"message":"General Error"}} 
POST https://api.cloudinary.com/v1_1/<**********>/upload 500 (Internal Server Error)

```javascript
        Upload.upload({
          url: 'https://api.cloudinary.com/v1_1/<**********>/upload',
          data: {
            file: file,
            public_id: fileId,
            upload_preset: '<**********>',
            context: 'alt=' + file.name + '|caption=' + file.name +  '|photo=' + file.name + '|$id=' + fileId,
            tags: [publicationId]
          }
        }).then(function (resp) {
          console.log('resp',resp);
        }, function (resp) {
          console.log('Error status: ' + resp.status);
        }, function (evt) {
          file.progress = Math.round((evt.loaded * 100.0) / evt.total);
        });
```
best regards.

**Comment by taragano** [comment]
I'm sorry for my response delay.
Do you still experience this issue? If so, can you please share the details and timestamp of a specific recent request, so we'll be able to try and take a look at it in our logs?

**Comment by romelgomez** [comment]
Hi, yes the issue still happening, i make a video to show you the issue, 

https://youtu.be/e94ls-T_Bnc

The first part of the video i show the file upload with: ng-file-upload 7.0.17, currently it is working properly. 

The second part i update to 12.0.1, and use the new syntax that ng-file-upload proposes. 

This is the time-stamp of the one recent request:

Access-Control-Allow-Methods:POST, GET, OPTIONS
Access-Control-Allow-Origin:http://localhost:8080
Access-Control-Max-Age:1728000
Cache-Control:no-cache
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Date:Sun, 14 Feb 2016 21:22:43 GMT
Server:cloudinary
Status:500 Internal Server Error
transfer-encoding:chunked
X-Cld-Error:General Error
X-Request-Id:7fb869745802348a
X-UA-Compatible:IE=Edge,chrome=1


Note: My native language is spanish, so sorry for the bad english.

**Comment by taragano** [comment]
Thank you for the additional information and video demonstration.

The problem is related to the way the `tags` parameter is serialized. You are using `tags[0]=...` which is currently not supported. Please try to either use `tags[]=...` or `tags=...` (the tags can be comma separated).

Let me know if this works for you?

**Comment by romelgomez** [comment]
Thanks @taragano , now it works: 

i change this: 
            tags: [publicationId]
for this: 
            tags: publicationId

**Comment by taragano** [comment]
@romelgomez - Our system was just updated, and we now support PHP style serialization of the `tags` parameter in upload and explicit APIs.
