### ISSUE TITLE
How to do responsive images

### ISSUE THREAD

**Issue by kishaningithub** [cloudinary/cloudinary_angular#49]
For the jquery version the doc is here
http://cloudinary.com/blog/how_to_automatically_create_images_for_responsive_design#api_example_2

How to do it with angular?

Setting width to auto and calling cloudinary.responsive() in controller does not work! 
In the above link the "responsive image" is in "data-src" as opposed to "src" but cl-image puts
image in "src" which gives the following error

```
https://res.cloudinary.com/<<my cloud name here>>/image/upload/c_scale,h_304,w_auto/<<my image id here>>
400 (Bad Request)'
```

**Comment by tocker** [comment]
Confirmed.
@kishaningithub thanks for reporting this!

**Comment by kishaningithub** [comment]
Any update on when this would be fixed?

**Comment by roeeba** [comment]
Hi, although a bit late, for prosperity, here's a code snippet that applies responsiveness on the image tag:

`<cl-image public-id="kit" responsive width="auto" crop="scale"></cl-image>`

**Comment by jackieros** [comment]
See also: https://docs-dev.cloudinary.com/documentation/angular_image_manipulation#responsive_image_settings
