### ISSUE TITLE
Upload preset must be whitelisted for unsigned uploads - question

### ISSUE THREAD

**Issue by VesperDev** [cloudinary/cloudinary_angular#51]
the following error hola que tal greetings to the community have the following questions when saving an image appears Cloudinary

`
$scope.uploadPic = function(file) {
      Upload.upload({
        url: "https://api.cloudinary.com/v1_1/" + cloudinary.config().cloud_name + "/image/upload",
        data: {
          upload_preset: cloudinary.config().upload_preset,
          tags: 'myphotoalbum',
          public_id: 'dwdw',
          context: 'photo=' + file.name,
          file: file
        }
      }).progress(function(e) {
        console.log(e);
      }).success(function(data, status, headers, config) {
        console.log(data, status, headers, config);
      }).error(function(data, status, headers, config) {
        console.log(data, status, headers, config);
      });

```
};`
```

![captura2](https://cloud.githubusercontent.com/assets/14016458/12880176/737ce2c4-ce03-11e5-998c-7aa1aadd8839.PNG)

and reestablished the Upload presets for testing and this error keeps coming.
How I can avoid this error?

**Comment by taragano** [comment]
As long as you use unsigned uploads, you should make sure that the upload preset you've defined is unsigned. This can be done via your account's [Upload settings page](https://cloudinary.com/console/settings/upload), click "Edit" next to your upload preset, and change its "Mode" to "Unsigned".

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues

**Comment by srinigithub2016** [comment]
"Upload preset must be specified when using unsigned upload" still error throwing after enabling Unsigned uploading enabled through admin console.

**Comment by srinigithub2016** [comment]
Hi,

i am using .net library to upload the file.

sample code snippet is below.

//intializing the account and creating cloudinary object
Account acccount = new Account(
_cloudinaryConfig.Value.CloudName,
_cloudinaryConfig.Value.APIKey,
_cloudinaryConfig.Value.APISecret
);
_cloudinary =new Cloudinary(acccount);



//upload the file stream with ImapgeUploadParams.
if(file.Length>0)
{
using (var stream = file.OpenReadStream())
{
var uploadParams= new ImageUploadParams()
{
File= new FileDescription(file.Name,stream),
UploadPreset="pknpynwm",
Transformation= new Transformation().Width(500).Height(500).Crop("fill").
Gravity("face")
};
uploadResult= _cloudinary.Upload(uploadParams);
}
}

**Comment by marissa-masangcay** [comment]
Hi @srinigithub2016,

We'd be happy to take a look at your logs if you could provide us with your cloud name. If you'd like to keep this information private please feel free to open a support ticket with us at the following link:

https://support.cloudinary.com/hc/en-us/requests/new

Also, have you tried passing in the parameter Unsigned = true with this call? Just as a side note as well, is there a particular reason that you want to perform an unsigned upload from the server side? You typically want to perform an unsigned upload when you're uploading from the Client side.
