### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by ctaepper** [cloudinary/cloudinary_angular#54]
i'd like to install this via npm (similar to the new pkg-cloudinary-core)

**Comment by buildjosh** [comment]
Any update on this?

**Comment by diegopamio** [comment]
I really need this too. Or at least a nice workaround.

**Comment by diegopamio** [comment]
I've just realized that there is a simple workaround, just use the full github url as the package name, and it works.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
