### ISSUE TITLE
feature-request: angular2 support?

### ISSUE THREAD

**Issue by cescoferraro** [cloudinary/cloudinary_angular#56]

**Comment by taragano** [comment]
It's on our road-map to officially support Angular 2. However there's no ETA for this yet.

**Comment by daohodac** [comment]
+1

**Comment by bjornharvold** [comment]
+1

**Comment by bjornharvold** [comment]
https://github.com/ekito/ng2-cloudinary

**Comment by taragano** [comment]
Hi All,

We're happy to update that we published our Angular 2.0 library. You can find the sources in the branch [angular_next](https://github.com/cloudinary/cloudinary_angular/tree/angular_next). You can install it using `npm` or `yarn` with the name `@cloudinary/angular`.

    npm install @cloudinary/angular
For more information:
http://cloudinary.com/blog/new_angular_sdk_for_image_management_more_than_meets_the_eye
