### ISSUE TITLE
tags fields not working

### ISSUE THREAD

**Issue by cavarzan** [cloudinary/cloudinary_angular#58]
Hi!

The `tags` fields seems to be not working. This is a sample of upload:

```
                     Upload.upload({
                        url: environment.cloudinary.upload,
                        data: {
                            upload_preset: environment.cloudinary.upload_preset,
                            tags: ['tag1', 'tag2'],
                            context: 'xxx',
                            file: base64
                        },
                        skipAuthorization: true
                    })
```

The context works fine, but I didn't receive in the response the tags fields created with these parameters.

Am I missing something?

**Comment by taragano** [comment]
Hi @cavarzan , 

Do you perform unsigned uploads or signed? Also, do you have tags defined on your upload preset?
Because if the upload preset has a tag definition, it will override the tags in the upload data. Otherwise tags are passed correctly.

**Comment by cavarzan** [comment]
@taragano Yes, I'm using defined tags in cloudinary, should be that! Thanks!
