### ISSUE TITLE
can you delete or update?

### ISSUE THREAD

**Issue by fabianrios** [cloudinary/cloudinary_angular#60]
if not can you point me in the right direction to try to contribute to do it, thanks

**Comment by taragano** [comment]
Hi @fabianrios,
Can you please share some more information regarding what specifically your requirements are?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues
