### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by kishaningithub** [cloudinary/cloudinary_angular#61]
Just a question on whether Angular 2 support is on your road map?

**Comment by Airswoop1** [comment]
+1

**Comment by bjornharvold** [comment]
+1 #bump

**Comment by bjornharvold** [comment]
https://github.com/ekito/ng2-cloudinary

**Comment by taragano** [comment]
It is indeed on our road-map to officially support Angular 2, however there's no ETA for this at the moment.
Thank you @bjornharvold for sharing the "ng2-cloudinary" repo. We'll be happy to check it out.

**Comment by tocker** [comment]
Hi All,

I'm happy to report that we published our Angular 2.0 library. You can find the sources in the branch [angular_next](https://github.com/cloudinary/cloudinary_angular/tree/angular_next). You can install it using `npm` or `yarn` with the name `@cloudinary/angular`.

```
npm install @cloudinary/angular
```

**Comment by taragano** [comment]
For more information about the new library's version:
http://cloudinary.com/blog/new_angular_sdk_for_image_management_more_than_meets_the_eye
