### ISSUE TITLE
Question: How to use eager transformation with this library?

### ISSUE THREAD

**Issue by vineshhpatel** [cloudinary/cloudinary_angular#62]

**Comment by MaorGariv** [comment]
You can pass the eager transformations in the [upload preset](http://cloudinary.com/documentation/upload_images#upload_presets) you specify for the upload.
This is a centralised way to control and normalise your uploads.
For more information,
http://cloudinary.com/blog/centralized_control_for_image_upload_image_size_format_thumbnail_generation_tagging_and_more

**Comment by MaorGariv** [comment]
Hi,

Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
