### ISSUE TITLE
 image id is not getting replaced in the public-id

### ISSUE THREAD

**Issue by sonalkadam9** [cloudinary/cloudinary_angular#63]
The image id is not getting replaced in the public-id. Can someone hlep me with this. Am i using it right?
1. Cloudinary HTML code :

```
<cl-image public-id="{profileImageId}" format="jpg" > 
                                <cl-transformation  height="150" width="150" crop="thumb" gravity="face" border="2px_solid_rgb:00390b60" /> 
                            </cl-image>
```
1. angular - controller:

$scope.profileImageId=userSession.getData().profileImageId;
1. Cloudinary request generated :

http://res.cloudinary.com/realint/image/upload/bo_2px_solid_rgb:00390b60,c_thumb,g_face,h_150,w_150/%7BprofileImageId%7D.jpg

**Comment by taragano** [comment]
Please try the following and let me know if it works for you? (double braces):

```
<cl-image public-id="{{profileImageId}}" format="jpg" > 
                                <cl-transformation  height="150" width="150" crop="thumb" gravity="face" border="2px_solid_rgb:00390b60" /> 
                            </cl-image>
```
Here's a reference:
https://github.com/cloudinary/cloudinary_angular/blob/a29230673bcb2912352429d0c2ac61c7581522f7/samples/photo_album_with_jquery/app/partials/photo-list.html#L59

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
