### ISSUE TITLE
Deleting Uploaded file from client side 

### ISSUE THREAD

**Issue by beeeku** [cloudinary/cloudinary_angular#64]
There is no documentation about how to delete a recently uploaded file from angular can you guide me about it .

**Comment by taragano** [comment]
Deleting from the client-side can be done up to 10 minutes after the images were uploaded.
This feature is documented here:
http://cloudinary.com/documentation/upload_images#deleting_client_side_uploaded_images

The `delete_by_token` helper method is currently available in our jQuery library only, it's on our road-map to add it to our Angular library too.

In the meantime, you can have a look at the jQuery code and implement it on your end:
https://github.com/cloudinary/pkg-cloudinary-jquery-file-upload/blob/master/cloudinary-jquery-file-upload.js#L3874-L3901

**Comment by rodriguezmanu** [comment]
`            var cloud_name = cloudinary.config().cloud_name,
                dataType = $.support.xhrFileUpload ? 'json' : 'iframe json',
                url = 'https://api.cloudinary.com/v1_1/' + cloud_name + '/delete_by_token';

            $http.post(url,
                {
                    token: file.result.delete_token
                },
                {
                    responseType: dataType,
                    headers: {
                        'X-Requested-With': 'XMLHttpRequest'
                    }
                })
                .then(function (response) {
                    console.log('success');
                }, function (response) {
                    console.log('err');
                });`

**Comment by eitanp461** [comment]
@beeeku You can also find a complete example in [this branch](https://github.com/cloudinary/cloudinary_angular/tree/delete-by-token).

It is based on the existing sample, and adds a "Delete me" button to uploaded images if a `delete_token` is returned by the upload request.

Note that you need to enable this functionality in your account in the settings page 
![image](https://cloud.githubusercontent.com/assets/3124855/22725970/3a85c48a-edd9-11e6-99dd-99ee2ec912e2.png)

**Comment by netstart** [comment]
If I add return_delete_token in the request, to get token i receive:
`X-Cld-Error:Return delete token parameter is not allowed when using unsigned upload. Only upload_preset,callback,public_id,folder,tags,context,face_coordinates,custom_coordinates upload parameters are allowed.`

How can i signed request? I Tried add in the below code in the  photo_album_aot sample
```
      form.append('api_key', '111111111');
      form.append('api_secret', '-111111111');
      form.append('timestamp', '1515760221');
      form.append('public_id', '1');
      form.append('overwrite', 'true');
      form.append('invalidate', 'true');
```

**Comment by eitanp461** [comment]
@netstart the `delete_token` is added automatically to the upload response once it is enabled in the upload preset. You shouldn't add it manually to the upload request.

You update this setting by:

1. Going to the settings/upload page in Cloudinary's administration console (https://cloudinary.com/console/settings/upload)
2. Click on "Edit" next to your unsigned upload preset
3. Click on "Advanced options"
4. Search for "Return delete token" in the page and update it to `Yes`
![image](https://user-images.githubusercontent.com/3124855/34916181-903afcc8-f93c-11e7-8d6c-88a6e2edc4a2.png)
5. click on "save"

Once enabled, you should see your upload preset as displayed in https://github.com/cloudinary/cloudinary_angular/issues/64#issuecomment-278241569

As for signed uploads - you shouldn't do this directly from the browser as it leaks your account's API key and secret.
If you wish to use signed uploads you need a backend where those parameters are secure. You upload the files to your backend and securely upload them to Cloudinary.

You can find a full example of using the delete token in the photo_album sample, e.g. https://github.com/cloudinary/cloudinary_angular/blob/master/samples/photo_album/app/js/photo-album/photo-upload.component.ts#L123

Hope this helps,
Eitan

**Comment by tuanhuu** [comment]
how to delete without 10 min

**Comment by idobarnoam** [comment]
@tuanhuu If you want to delete resources after 10 minutes has passed you would need to use other methods which are available in our authenticated API. 

Either by using the [Destroy method](https://cloudinary.com/documentation/image_upload_api_reference#destroy_method) of the upload API or use the [Delete method](https://cloudinary.com/documentation/admin_api#delete_resources) of the admin API.

**Comment by tuanhuu** [comment]
> @tuanhuu If you want to delete resources after 10 minutes has passed you would need to use other methods which are available in our authenticated API.
> 
> Either by using the [Destroy method](https://cloudinary.com/documentation/image_upload_api_reference#destroy_method) of the upload API or use the [Delete method](https://cloudinary.com/documentation/admin_api#delete_resources) of the admin API.

thank u, i will try

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
