### ISSUE TITLE
NamedNodeMap check causes Firefox Gecko <34 to crash

### ISSUE THREAD

**Issue by schugh** [cloudinary/cloudinary_angular#65]
Need to add typeof check before attempting to evaluate NamedNodeMap

var isNamedNodeMap = source && (source.constructor.name === "NamedNodeMap" || source instanceof NamedNodeMap)

to

var isNamedNodeMap = source && (source.constructor.name === "NamedNodeMap" || (typeof NamedNodeMap != 'undefined' && source instanceof NamedNodeMap));

**Comment by schugh** [comment]
Any word on this? Should be a direct swap out of the line. We still have number non-trivial number of folks that can't our web app because of this

**Comment by tocker** [comment]
Fixed by #67

**Comment by schugh** [comment]
Thanks for getting to this; seems that the fix isn't complete though. 

You still need the typeof check in both if blocks (original post) to prevent attempted evaluation of NamedNodeMap object crashing the webpage. 

![image](https://cloud.githubusercontent.com/assets/2747760/22000039/f946e1e6-dbf1-11e6-91dd-77cc84df0d26.png)

Do give it a test run in a Mozilla browser pre 34 to reproduce the behavior: https://ftp.mozilla.org/pub/firefox/releases/33.1/

**Comment by eitanp461** [comment]
Hi

The fix was verified on Firefox 33 before the merge.
Since we haven't published a release yet, you'll have to adjust your bower.json to install the fixed version manually:

Replace `"cloudinary_ng": "~1.0.0"` with `"cloudinary_ng": "#c7301f0"` in your `bower.json` and run `bower install` to get the latest code.

Let me know if it works for you.

**Comment by schugh** [comment]
Ah, I didn't see that it wasn't merged.  I'll give it a go. Thank you!

**Comment by schugh** [comment]
Just confirmed using the commit tag. thanks again for following up and
making the fix!
