### ISSUE TITLE
Unable to upload image at a specific transformation and width

### ISSUE THREAD

**Issue by iamakimmer** [cloudinary/cloudinary_angular#66]
I'm trying to specify a width here but it's still saving the original image. How can I specify a crop with limit and width 600? 

`        Upload.upload({
          url: "https://api.cloudinary.com/v1_1/myfolder/upload",
          data: {
            crop: 'limit',
            width: 600,
            folder: window.location.host,
            upload_preset: 'abcd',
            file: file
          }
        })`

**Comment by taragano** [comment]
Do you perform unsigned uploads? If you do, then note that unsigned uploads do not support defining an incoming transformation as part of the dynamic upload options. To apply this transformation, you'll need to define this in the upload preset's settings.
Let me know if this works for you?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
