### ISSUE TITLE
import { CloudinaryModule, CloudinaryConfiguration, provideCloudinary } from 'cloudinary-ng';

### ISSUE THREAD

**Issue by bjornharvold** [cloudinary/cloudinary_angular#68]
'cloudinary-ng' does not exist. Probably best to update README.MD

**Comment by eitanp461** [comment]
Thanks!
We missed to rename that reference with the new name
Fixed by https://github.com/cloudinary/cloudinary_angular/commit/aa6170fe90f4365ac08f61a2dbea3a2996e85c02
