### ISSUE TITLE
Using require() with Angular CLI

### ISSUE THREAD

**Issue by bjornharvold** [cloudinary/cloudinary_angular#69]
require() is internal to NodeJS and not available to users of Angular CLI if I am not mistaken. I cannot use this code as it fails.

provideCloudinary(require('cloudinary-core'), { cloud_name: 'your_cloud_name' } as CloudinaryConfiguration)

**Comment by eitanp461** [comment]
`require` is meant to be resolved by the module loader. 
Our examples show usage of either Webpack or SystemJS.

Angular CLI is in fact using Webpack ([reference](https://github.com/angular/angular-cli#webpack-update)) so it should be ok.

Can you share additional details if you're experiencing problems?

**Comment by bjornharvold** [comment]
Hi,

This is what I get when I import your library into my app:

> ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 51:51 in the original .ts file), resolving symbol SharedModule in /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/shared/shared.module.ts
> 
> ERROR in ./src/app/shared/shared.module.ts
> Module build failed: Error: /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/shared/shared.module.ts (51,23): Cannot find name 'require'.)
> /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/shared/shared.module.ts (51,51): Cannot find name 'cloudinaryConfiguration'.)
>     at _checkDiagnostics (/Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@ngtools/webpack/src/loader.js:116:15)
>     at /Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@ngtools/webpack/src/loader.js:141:17

<img width="762" alt="screengrab" src="https://cloud.githubusercontent.com/assets/641791/21974006/cb341b98-dbf6-11e6-9ed2-14afac765bc5.png">

**Comment by eitanp461** [comment]
`require` is used by the package loader, and is supported by Webpack and SystemJS. 
Which one are using?

Nonetheless you can `import` cloudinary-core the same way you import other modules in the top of the file.

Add the following import statement to the head of the file
`import {Cloudinary} from 'cloudinary-core';`

And replace provideCloudinary with the following:
`provideCloudinary({Cloudinary}, cloudinaryConfiguration as CloudinaryConfiguration)`

**Comment by bjornharvold** [comment]
This was helpful and got me a little further. Here's the next error.

```
ERROR in Error encountered resolving symbol values statically. Calling function 'provideCloudinary', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/app.module.ts, resolving symbol AppModule in /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/app.module.ts

ERROR in ./src/app/app.module.ts
Module build failed: Error: /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/app.module.ts (12,26): Cannot find module 'cloudinary-core'.)
    at _checkDiagnostics (/Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@ngtools/webpack/src/loader.js:145:15)
    at /Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@ngtools/webpack/src/loader.js:172:17
 @ ./src/main.ts 8:0-45
 @ multi main

```

I think this is a limitation imposed by Angular since 2.4 to make all 3rd party modules be AoT compliant. ng2-translate had a fix for this and did something like this:

```
export function createTranslateLoader(http: Http) {
  return new TranslateStaticLoader(http, '/assets/i18n', '.json');
}

imports: [
   TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (createTranslateLoader),
      deps: [Http]
    }),
]
```

**Comment by eitanp461** [comment]
We've published a new version to NPM with AOT support (2.1.1), and a reference [sample project that uses it](https://github.com/cloudinary/cloudinary_angular/tree/angular_next/samples/photo_album_aot).

Note the new syntax for providing Cloudinary in [app.module.ts](https://github.com/cloudinary/cloudinary_angular/blob/angular_next/samples/photo_album_aot/app/js/app.module.ts) that uses forRoot

**Comment by bjornharvold** [comment]
Hi,

I've followed the instructions in your sample project and am now getting a different error.

```
import {Cloudinary} from 'cloudinary-core/cloudinary-core-shrinkwrap';
import {CloudinaryModule} from '@cloudinary/angular';

export const config = {
  cloud_name: 'traveliko',
  upload_preset: 'traveliko_default_preset'
};

const cloudinaryLib = {
  Cloudinary: Cloudinary
};
```

In imports I write:

`CloudinaryModule.forRoot(cloudinaryLib, config),`

Error I get now:

ERROR in Error encountered resolving symbol values statically. Could not resolve cloudinary-core/cloudinary-core-shrinkwrap relative to /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/app.module.ts., resolving symbol AppModule in /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/app.module.ts, resolving symbol AppModule in /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/app.module.ts, resolving symbol AppModule in /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/app.module.ts

```
ERROR in ./src/app/app.module.ts
Module build failed: Error: /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/app.module.ts (21,26): Cannot find module 'cloudinary-core/cloudinary-core-shrinkwrap'.)
    at _checkDiagnostics (/Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@ngtools/webpack/src/loader.js:145:15)
    at /Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@ngtools/webpack/src/loader.js:172:17
 @ ./src/main.ts 8:0-45
 @ multi main
```

I can see that your shrinkwrap js files exists but my app is not picking it up.

Please advise

**Comment by bjornharvold** [comment]
Just to recap:

- The app uses Angular CLI latest
- The app uses many other 3rd party libraries without any issues
- The only time I had a slightly similar issue was when a vendor did not make some classes available

**Comment by eitanp461** [comment]
I've added the [rollup-config.js](https://github.com/cloudinary/cloudinary_angular/blob/angular_next/samples/photo_album_aot/rollup-config.js) file to our AOT sample, which was excluded by mistake from the previous commit.

Please see if it helps with your latest issue.

**Comment by bjornharvold** [comment]
I'm looking at how you import cloudinary-core using commonjs. Angular CLI uses web pack under-the-hood. If you could show me how you would do it using web pack it would be greatly appreciated.

IntelliJ doesn't really complain in red when I do the import but Angular CLI definitely complains when trying to compile.

If I cmd-click on the cloudinary-core import it can find the node_module library. It doesn't resolve the shrinkwrap js though. The CloudinaryModule works fine.

**Comment by eitanp461** [comment]
You can use [webpack resolve alias](https://webpack.github.io/docs/configuration.html#resolve-alias) to load the shirnkwrap version of cloudinary-core.

I updated our sample application that uses Webpack with an [example](https://github.com/cloudinary/cloudinary_angular/commit/ea03117395379761124f865cffac8748a23a41c1)

**Comment by ronbelson** [comment]
Hi,

The same problem with Angular cli:
can't find the file
import { Cloudinary } from 'cloudinary-core/cloudinary-core-shrinkwrap';

"@angular/compiler-cli": "^2.3.1",
        "@types/hammerjs": "^2.0.34",
        "@types/jasmine": "2.5.38",
        "@types/node": "^6.0.42",
        "angular-cli": "1.0.0-beta.25.5",

didn't have tha  webpack resolve alias  on angular cli project
![screen shot 2017-01-19 at 5 09 03 pm](https://cloud.githubusercontent.com/assets/1230182/22112027/411061bc-de6a-11e6-99bb-2558b6d4ad6d.png)

Thanks,

Ron

**Comment by bjornharvold** [comment]
Angular CLI currently does not expose webpack.config.js as you can see here: https://github.com/angular/angular-cli/issues/1656 so resolve / alias will not work. Only thing you have available to you is angular-cli.json where you can import scripts like so:

```
"styles": [
        "styles.less",
        "../node_modules/sweetalert2/dist/sweetalert2.min.css"
      ],
      "scripts": [
        "../node_modules/sweetalert2/dist/sweetalert2.min.js"
      ],
```

Would be appreciated if you can create a small sample Angular CLI project and show how this could be done. So far I cannot move forward on this.

**Comment by ronbelson** [comment]
Tried the import didn't work...
Also tried to add typings.d.js with:
declare module 'cloudinary-core';
declare module 'lodash';

On the root of the project

Nothing yet to fix this..

**Comment by eitanp461** [comment]
I've added a new sample created with Angular CLI.

Notice that due to the limitations in Angular CLI project ([not exposing resolve aliases, not having an addon system ready yet](https://github.com/angular/angular-cli/issues/1656#issuecomment-240171375)) you need to `npm install lodash` since `cloudinary-core` depends on it.

Once an addon system for Angular CLI will be published, you should be able to use it to import the `cloudinary-core-shrinkwrap` version instead using an alias and remove the lodash dependency.

Also, note the addition of `typings.d.ts` under the `src` folder of the CLI sample with:
```javascript
declare module 'cloudinary-core';
```

`app.module.ts` looks like this

```javascript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { CloudinaryModule } from '@cloudinary/angular';

import { AppComponent } from './app.component';

import * as  Cloudinary from 'cloudinary-core';

@NgModule({
  declarations: [
    AppComponent
    ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    CloudinaryModule.forRoot(Cloudinary, { cloud_name: 'demo'}),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

And I added a `cl-image` element to `app.component.html`:

```html
<h1>
  {{title}}
</h1>
<cl-image public-id="sample" width="500">

</cl-image>
```

**Comment by bjornharvold** [comment]
Trying this out now. Eitan's sample can be found here: https://github.com/cloudinary/cloudinary_angular/tree/angular_next/samples/angular-cli-sample

**Comment by bjornharvold** [comment]
@eitanp461 !

Good solve. Works like a charm. Great work. Your understanding of the internals here is +++.

**Comment by eitanp461** [comment]
@bjornharvold Thanks for the kind feedback. Appreciated.

**Comment by bogacg** [comment]
@eitanp461 thanks for this solution. I've tried it and wanted to go further:
Two questions: 
**1. How can I use Cloudinary SDK functions after adding it this way.**
Example (what used to be):
```
var cl = cloudinary.Cloudinary.new({cloud_name: "<mycloudID>"});
var clEncoddedURL = cl.url('http://somedomain.com/images/image.jpg', {type: "fetch"});
```
**2.Why am I getting this error: `Can't bind to 'clHref' since it isn't a known property of 'a'`?**

**Comment by eitanp461** [comment]
@bogacg would you care to share your findings via a branch in this repository?

Do you currently need any assistance from our team?

**Comment by bogacg** [comment]
@eitanp461 thank you, right now I'm good. Sure I'd be happy to help. I can share example project and what changes I did so that you can see those steps better.

**Comment by eitanp461** [comment]
@bogacg that would be great. I'd be happy to see your changes for a better understanding of this use case. Thanks!

**Comment by adriendomoison** [comment]
@eitanp461 it looks like the angular-cli sample is not working anymore with the latest version of angular-cli, and I completly failed to find out what's going on x(

**Comment by eitanp461** [comment]
@adriendomoison I got `ng serve --aot` to work when adding a type definition to cloudinary-core as suggested in [this pull request](https://github.com/cloudinary/cloudinary_js/pull/120).
I applied the changes locally within my `node_modules/cloudinary-core`.

I will work towards merging the PR in `cloudinary_js` repository and will update here once fully resolved.

**Comment by adriendomoison** [comment]
@eitanp461 thanks ! This definitely need to be merged since there are no way to make that work in production right now :(

**Comment by eitanp461** [comment]
@adriendomoison I opened a new pull request that adds a type definition file to `cloudinary-core`.
You can follow its status here https://github.com/cloudinary/cloudinary_js/pull/122

**Comment by adriendomoison** [comment]
Yuhuuu !! Any idea when this will be integrated? I have to make the decision if I switch to https://github.com/ekito/ng2-cloudinary temporary ... and I feel super lazy to have to do it if is for a few days only x)
Thank you :D

**Comment by roeeba** [comment]
Hi @adriendomoison, we're aiming at integrating this by the end of this week. Stay tuned :)

**Comment by roeeba** [comment]
This issue was resolved in March. Please refer to - https://github.com/cloudinary/cloudinary_angular/issues/77
