### ISSUE TITLE
bower main file not found

### ISSUE THREAD

**Issue by nhim175** [cloudinary/cloudinary_angular#71]
I've just installed v2.1.1 and I don't see the main file anywhere

**Comment by eitanp461** [comment]
@nhim175 Version 2.1.1 is our Angular2 SDK.
It is not using Bower - we're using `npm` or `yarn` for installing its dependencies, which are listed in `package.json`.

Our Angular1 SDK is using Bower. 
If you need that then you can install it with `npm install --save cloudinary-angular`
