### ISSUE TITLE
Angular 2 deployment issue (new Angular CLI - RC version)

### ISSUE THREAD

**Issue by fibinger** [cloudinary/cloudinary_angular#73]
Hi,

My Angular 2 application works fine in dev mode. However when I built it and deployed the following error related to Cloudinary Angular was displayed:
`TypeError: Cannot read property 'CloudinaryJQuery' of null`
Looks like variable **cloudinaryJsLib** in _cloudinary.service.js_ is not defined.
I am wondering what might be the problem?

Important node:
angular-cli-sample attached to this project is using old version of angular-cli (still in BETA), whereas new RC version is much different. It would be very convenient to have some reference code to rely on.

**Comment by DennisSmolek** [comment]
Not sure exactly your issue but I'm guessing it's related to the package branch being out of date. I've submitted a PR #75 which updates the package and clears the `opaqueToken` issue.

Until it gets checked out just copy my /src folder and put it wherever. Change your `import` to point to `cloudnary.module` in that folder and it should all work as expected.

**Comment by fibinger** [comment]
We're using different versions of Angular, I am using Angular 2 which supports opaque tokens, and you're using Angular 4. Therefore we're talking about distinct issues.

**Comment by fibinger** [comment]
You're right. The issue is related to AOT. Unfortunately nothing nothing solved the problem.
Please carry on talking in #77

**Comment by lujakob** [comment]
For me a downgrade to 
`    "cloudinary-core": "^2.3.0",
`
solved it the 
`TypeError: Cannot read property 'CloudinaryJQuery' of null
`
