### ISSUE TITLE
Will not work on Angular 4.0.0.rc3

### ISSUE THREAD

**Issue by bjornharvold** [cloudinary/cloudinary_angular#74]
ERROR in Error encountered resolving symbol values statically. Calling function 'OpaqueToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol CLOUDINARY_LIB in /Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@cloudinary/angular/src/cloudinary.module.d.ts, resolving symbol CloudinaryModule.forRoot in /Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@cloudinary/angular/src/cloudinary.module.d.ts, resolving symbol AppModule in /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/app.module.ts, resolving symbol AppModule in /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/app.module.ts.

Please advise,
Bjorn

**Comment by DennisSmolek** [comment]
It's a super simple fix. I've submitted a PR #75 which fixes this issue

**Comment by bjornharvold** [comment]
Bump. Can I please have a timeline on this issue? There are also some other outstanding issues here on this board that prevents me to take this library to production.

Cheers
Bjorn

**Comment by bjornharvold** [comment]
Angular 4.0.0 and Angular CLI 1.0.0 have been released. Can we get a fix on this please.

**Comment by eitanp461** [comment]
@bjornharvold We are working out the details on the best solution for supporting both Angular 2.x and 4.x libraries. 
I will update as soon as we finalize the solution and publish a 4.x compatible SDK.

**Comment by bjornharvold** [comment]
Thank you for getting back to me on a Sunday @eitanp461 and for keeping me updated :-)

**Comment by DennisSmolek** [comment]
As the version `2.x` to `4.x` has breaking changes I don't think you'll be able to support both without having two totally different packages.. I would just use the current branch as the last one to support `< 4.0` and move forward.. `4.x` I think will be a much better base moving forward...

**Comment by zpydee** [comment]
pls can we have a ETA for this fix?

**Comment by roeeba** [comment]
Hi, We're aiming to add support for Angular 4.x by the end of this month (April). We will update here as soon as it is available.

**Comment by bjornharvold** [comment]
Thanks for the update @roeeba! As Angular 2 was really just a preparation for a more solid version of Angular in v4, I don't think any developer will be sticking around on Angular 2 if they don't absolutely have to.

**Comment by bjornharvold** [comment]
Hi guys!

It's the end of the month. Any updates @roeeba? @eitanp461 

I'm really waiting on this so I can take my apps to production. Ideally in less than 7 days :-)

Cheers

**Comment by roeeba** [comment]
Hi @bjornharvold, we're on it :) and we're doing our best to meet the deadline. Stay tuned for updates.

**Comment by bjornharvold** [comment]
Cheers guys :-) @roeeba @eitanp461 I see you guys are very busy in the repo. Appreciate the quick response. FYI I am an evangelist for Cloudinary. For any startup I say to go with you guys. It's a no-brainer!!

Keep up the good work

**Comment by dottodot** [comment]
Any new on the fix for this as it's preventing me from creating a production build.

**Comment by roeeba** [comment]
Hi @bjornharvold, @dottodot, If everything will be going according to our plan, we'll be publishing support for Angular 4 later this week. We will update as soon as that happens. 

@bjornharvold, thank you very much for your support and great feedback! :) we extremely appreciate it!

**Comment by bjornharvold** [comment]
Hi guys! How is progress going?

**Comment by fibinger** [comment]
Seems like you have forgotten about us. To be honest it's really blocking us, cloudinary_angular upgrade is crucial for our project.

**Comment by tocker** [comment]
Hi All.
We are resolving a few issues related to the re-packaging. Will publish very soon.

**Comment by tocker** [comment]
The new code has been published. Please try `npm install @cloudinary/angular-4.x`. 

npm link: https://www.npmjs.com/package/@cloudinary/angular-4.x

**Comment by bjornharvold** [comment]
Working! Solid work :-) 👍
