### ISSUE TITLE
ng serve ERROR OpaqueToken resolving CLOUDINARY_LIB

### ISSUE THREAD

**Issue by ukmadlz** [cloudinary/cloudinary_angular#79]
I'm getting the following error:

```
ERROR in Error encountered resolving symbol values statically. Calling function 'OpaqueToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol CLOUDINARY_LIB in /home/mike/Development/angular2-cloudinary-progressive-web-app/node_modules/@cloudinary/angular/src/cloudinary.module.d.ts, resolving symbol CloudinaryModule.forRoot in /home/mike/Development/angular2-cloudinary-progressive-web-app/node_modules/@cloudinary/angular/src/cloudinary.module.d.ts, resolving symbol AppModule in /home/mike/Development/angular2-cloudinary-progressive-web-app/src/app/app.module.ts, resolving symbol AppModule in /home/mike/Development/angular2-cloudinary-progressive-web-app/src/app/app.module.ts
```
The code in question is
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { RouterModule } from '@angular/router';

import { Cloudinary } from 'cloudinary-core';
import { CloudinaryModule } from '@cloudinary/angular';

import { AppComponent } from './app.component';
import { PhotoThumbComponent } from './photo-thumb/photo-thumb.component';
import { HomeComponent } from './home/home.component';
import { ViewComponent } from './view/view.component';

import { routes } from './app.routes';

export const cloudinaryLib = {
  Cloudinary: Cloudinary
};

@NgModule({
  declarations: [
    AppComponent,
    PhotoThumbComponent,
    HomeComponent,
    ViewComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    CloudinaryModule.forRoot(cloudinaryLib, { cloud_name: 'elsmore-me'}),
    RouterModule.forRoot(routes)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
I can't see anything wrong, and even more confusingly it'll build if I just save at random

**Comment by bjornharvold** [comment]
+1 My developers are randomly seeing this as well. This issue came with the latest cloudinary-core update.

**Comment by adriendomoison** [comment]
Hello,

The error prevent to compile with AOT.
Here is the full error I get:

```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /home/john/dev/project/node_modules/@cloudinary/angular/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /home/john/dev/project/node_modules/@cloudinary/angular/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /home/john/dev/project/node_modules/@cloudinary/angular/node_modules/@angular/core/src/di/opaque_token.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/john/dev/project/src'
 @ ./src/main.ts 4:0-74
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

I never have been able to use Cloudinary and AOT from now ^^

**Comment by roeeba** [comment]
Hey guys, sorry for the delayed reply. We're aware of this issue and are working on fixing this. Update to follow.

**Comment by mflorence99** [comment]
I started to see this issue repeatedly so based on the notes above I backed off to `"cloudinary-core": "2.2.1"` -- but sadly the error is still there.

**Comment by tontonwappy** [comment]
have the same issue ...

**Comment by dottodot** [comment]
Any news on when this will be fixed?

**Comment by roeeba** [comment]
Hi, guys. A fix was published yesterday.
Please let us know if you still see an issue.

**Comment by trencoret** [comment]
Problem is still there with versions `@cloudinary/angular@2.1.1` and `cloudinary-core@2.3.0`

Trying to run your sample angular-cli-sample and this is the error: 
`ERROR in Error encountered resolving symbol values statically. Calling function 'OpaqueToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol CLOUDINARY_LIB in ...`

**Comment by tocker** [comment]
@trencoret and all, please update the dependency to "@cloudinary/angular-4.x" version "1.0.0".
Let us know if it solves your issue!

**Comment by ukmadlz** [comment]
@tocker is the 4.0 backwardly compatible with 2.0?

**Comment by eitanp461** [comment]
@trencoret I just tested the `angular-cli-sample` for our Angular2 SDK from https://github.com/cloudinary/cloudinary_angular/tree/angular-2.x branch, and did not witness any errors. 
Can you try deleting your local `node_modules` and reinstalling with `yarn install` just to make sure there are no leftovers there?

@ukmadlz The SDK for Angular4 is not backwards compatible with Angular2. It is using InjectionToken which is [new in Angular4](https://blog.thoughtram.io/angular/2016/05/23/opaque-tokens-in-angular-2.html#injectiontoken-since-angular-4x)

**Comment by carloinqbyteio** [comment]
I have solved mine, I am using Yarn, I had to delete **node_modules** and **yarn.lock** (if you're using npm, delete **package.lock.json**).

Run yarn install or npm install again.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
