### ISSUE TITLE
alt and title tags

### ISSUE THREAD

**Issue by dottodot** [cloudinary/cloudinary_angular#82]
How do you add these?

Tried adding it to the `cl-image` tag but gives an error of

> Can't bind to 'alt' since it isn't a known property of 'cl-image'

**Comment by roeeba** [comment]
Hi @dottodot, our dev team is reviewing your inquiry. We will update soon with our insights.

**Comment by eitanp461** [comment]
@dottodot You can add alt and title attributes with the following syntax:
```
<cl-image 
   public-id="sample"
   [attr.title]="tooltip()"
   [attr.alt]="alt()">
</cl-image>
```

See an example here - https://codepen.io/eitanp461/project/editor/DYBzvZ/
