### ISSUE TITLE
Changing public_id with observables

### ISSUE THREAD

**Issue by smsami** [cloudinary/cloudinary_angular#83]
Here is an issue I found with the cl-image tag. Given the following:

_user is a BehaviorSubject, which is undefined initially and is defined in the constructor of a component.

<cl-image [public-id]="(_user | async)?.logo" width="100%" height="auto"></cl-image>

if the _user is updated, the cl-image does get updated and the image changes ONLY AND ONLY if "enableProdMode" is disabled.

This has been tested in Angular2.

**Comment by eitanp461** [comment]
@smsami Thanks for reporting this.

Can you reproduce the issue in Plunker? You can fork https://plnkr.co/edit/e4GuRg?p=info  to get you started.

**Comment by fibinger** [comment]
@eitanp461 Here you go the Plunker:

https://plnkr.co/edit/LQMrPSQJJYMbRdmpBvDK?p=preview

Click on "Change public ID" button to reproduce the problem.

If you comment out the line
`enableProdMode();`
it will start working.

**Comment by eitanp461** [comment]
@fibinger thank you for the sample, it was a great help!
I opened a PR with a fix, and will take it further with @tocker

**Comment by ctaepper** [comment]
this was closed exactly one month ago and it is not published to npm yet... whats the holdup?
