### ISSUE TITLE
Can't resolve all parameters for Cloudinary: (?).

### ISSUE THREAD

**Issue by ManjuSagar** [cloudinary/cloudinary_angular#86]
I am getting this error after doing all the steps!

**Comment by eitanp461** [comment]
@ManjuSagar Can you please provide additional details? 
1. Which Angular version are you using?
2. Which Cloudinary SDK version?
3. What is the error you see?

**Comment by Nazar-bnm** [comment]
I have the same problem - Uncaught Error: Can't resolve all parameters for Cloudinary: (?) 
I use Angular 4.1.3, Cloudinary 1.0.0

**Comment by eitanp461** [comment]
@Nazar-bnm Can you please provide additional details?
Can you share the module configuration?
Do our samples work for you?

**Comment by Nazar-bnm** [comment]
`import { NgModule, ErrorHandler } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { BrowserModule } from '@angular/platform-browser';

import {IonicApp, IonicModule, IonicErrorHandler, Config, PageTransition, Animation} from 'ionic-angular';

import { Facebook } from '@ionic-native/facebook';
import { EmailComposer } from '@ionic-native/email-composer';
import { HttpModule } from '@angular/http';
import { NativePageTransitions } from '@ionic-native/native-page-transitions';

import { MyApp } from './app.component';

import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { Network } from "@ionic-native/network";

import { AuthService } from '../providers/auth/auth';
import { ContainersProvider } from '../providers/containers/containers';
import { PickupProvider } from '../providers/pickup/pickup';
import { BasicDataProvider } from '../providers/basic-data/basic-data';
import { TabsService } from '../providers/tabs.service';
import { InviteCodeProvider } from '../providers/signup/inviteCode';
import { SignupService } from '../providers/signup/signup';

import { HttpClient } from "../providers/http.client";
import { IonicStorageModule } from "@ionic/storage";

import { MultiPickerModule } from 'ion-multi-picker';
import { Camera, CameraOptions } from '@ionic-native/camera';
import { FileTransfer } from '@ionic-native/file-transfer';
import { CloudinaryModule, CloudinaryConfiguration } from '@cloudinary/angular';
import { Cloudinary } from 'cloudinary-core';

@NgModule({
  declarations: [
    MyApp
  ],
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    MultiPickerModule,
    IonicModule.forRoot(MyApp, { mode: 'ios', backButtonText: ' ',  pageTransition: 'fade'}),
    IonicStorageModule.forRoot({
      name: '__mydb',
      driverOrder: ['indexeddb', 'sqlite', 'websql']
    }),
    CloudinaryModule.forRoot({Cloudinary}, { cloud_name: 'xxxxxx' } as CloudinaryConfiguration),
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp
  ],
  providers: [
    StatusBar,
    SplashScreen,
    Facebook,
    Cloudinary,
    EmailComposer,
    AuthService,
    ContainersProvider,
    PickupProvider,
    BasicDataProvider,
    TabsService,
    InviteCodeProvider,
    SignupService,
    HttpClient,
    Network,
    NativePageTransitions,
    Camera,
    FileTransfer,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
   ]
})
export class AppModule { constructor(config: Config) {
  config.setTransition('fade', FadeTansition);
}
}`

**Comment by eitanp461** [comment]
@Nazar-bnm remove `Cloudinary` from the providers array

**Comment by Nazar-bnm** [comment]
Thanks for your fast answer. But I tried it and in this case I have another error - ERROR Error: Uncaught (in promise): Error: No provider for Cloudinary!

**Comment by eitanp461** [comment]
@Nazar-bnm can you share the code where you get this error?
See also this minimalistic example of the SDK usage - https://codepen.io/eitanp461/project/editor/DYBzvZ

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
