### ISSUE TITLE
Broken link to Angular1 documentation

### ISSUE THREAD

**Issue by kristynrb** [cloudinary/cloudinary_angular#89]
When you click on the link to the Angular1 documentation, it takes you to a page with a 404.

The line in the README: "Cloudinary's AngularJS (AKA Angular1) SDK can be found here"
The link with the 404: https://github.com/cloudinary/cloudinary_angular/tree/angular-1

**Comment by eitanp461** [comment]
@kristynrb Thanks for reporting this. Fixed.
