### ISSUE TITLE
angular 1 1.64 not work

### ISSUE THREAD

**Issue by yaroslavert** [cloudinary/cloudinary_angular#90]
Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:unpr] Unknown provider: cloudinaryProvide

**Comment by eitanp461** [comment]
@yaroslavert Which Cloudinary SDK version are you using?
We're publishing an SDK for different Angular versions.

Make sure you're on our AngularJS one.
You can find setup details [here](https://github.com/cloudinary/cloudinary_angular/tree/angular-1.x)
