### ISSUE TITLE
Cannot read property 'CloudinaryJQuery' of null

### ISSUE THREAD

**Issue by murunwas** [cloudinary/cloudinary_angular#92]
when I build with the production flag it works fine but when you deploy to the server  I get "Cannot read property 'CloudinaryJQuery' of null" error

**Comment by eitanp461** [comment]
@murunwas Can you link to the deployment?
Can you share your module.ts that initializes the Cloudinary module?
What tools are you using for build/deploy? Vanilla Webpack / Angular CLI / Other?

**Comment by murunwas** [comment]
@eitanp461 I'm using angular CLI, "ng build" works fine but "ng build --prod" I get "Cannot read property 'CloudinaryJQuery' of null" error
![screenshot_20170720082156](https://user-images.githubusercontent.com/8838943/28403341-97d277b2-6d24-11e7-8bb9-fa9fa7ed1f20.png)
![image](https://user-images.githubusercontent.com/8838943/28403533-64ecfc9a-6d25-11e7-81a1-260af6ded6a6.png)

**Comment by eitanp461** [comment]
@murunwas Angular CLI is strict with what it expects to receive, and how it is defined.

Angular CLI prod mode works by setting the `cloudinaryLib` as a const and providing the config parameters inline as follows:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { Cloudinary } from 'cloudinary-core';
import { CloudinaryModule } from '@cloudinary/angular-4.x';
import cloudinaryConfiguration from './config';
import { AppComponent } from './app.component';

export const cloudinaryLib = {
  Cloudinary: Cloudinary
};

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    CloudinaryModule.forRoot(cloudinaryLib, {
      cloud_name: 'your cloud name',
      upload_preset: 'optional upload preset'
    }),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

I will update our sample once you confirm this resolves the issue.

**Comment by murunwas** [comment]
Thanks alot @eitanp461 it is working fine now with the "ng build --prod"

**Comment by eitanp461** [comment]
Happy it worked. I will update the sample code and docs.

**Comment by arifullahjan** [comment]
Still givess RROR TypeError: cloudinaryJsLib.Cloudinary is not a constructor
    at new Cloudinary (vendor.js:122171)
    at createCloudinary (vendor.js:122052)
    at _callFactory (vendor.js:61873)
    at _createProviderInstance$1 (vendor.js:61827)
    at resolveNgModuleDep (vendor.js:61790)
    at N 
Angular 6 
used both 4.x and 5.x

**Comment by strausr** [comment]
@arifullahjan Can you provide more information on your setup? Please take a look at our sample projects that implement the required setup for each Angular version https://github.com/cloudinary/cloudinary_angular/tree/angular-2.x/samples
